### ISSUE TITLE
Shirt/Pants Commands Often Display Wrong/No Clothing

### ISSUE THREAD

**Issue by ChocoIate** [Sceleratis/Adonis#100]
When using the ':shirt (Username) (ID)' and ':pants (Username) (ID)', the clothing displayed is rarely correct.

**Comment by ChocoIate** [comment]
':hat (Username) (ID)' command seems to work just fine though, not sure why one works and the other has bugs.

**Comment by ChocoIate** [comment]
After looking into it more, the script just seems to search for the first image ID lower than the ID, disregarding whether the ID matches.

**Comment by ChocoIate** [comment]
Edited Shirt/Pants Commands in MainModule.Server.Core.Commands and changed them to:

Shirt = {
			Prefix = Settings.Prefix;
			Commands = {"shirt";"giveshirt";};
			Args = {"player";"ID";};
			Hidden = false;
			Description = "Give the target player(s) the shirt that belongs to <ID>";
			Fun = false;
			AdminLevel = "Moderators";
			Function = function(plr,args)
				for i,v in pairs(service.GetPlayers(plr,args[1])) do
						if v.Character then
							for g,k in pairs(v.Character:children()) do
								if k:IsA("Shirt") then k:Destroy() end
							end
							local shirttt = game:GetService("InsertService"):LoadAsset(args[2])
							if shirttt.Shirt ~= nil then
								shirttt.Shirt.Parent = v.Character
							end
						end
				end
			end
		};
		
		Pants = {
			Prefix = Settings.Prefix;
			Commands = {"pants";"givepants";};
			Args = {"player";"id";};
			Hidden = false;
			Description = "Give the target player(s) the pants that belongs to <id>";
			Fun = false;
			AdminLevel = "Moderators";
			Function = function(plr,args)
				for i,v in pairs(service.GetPlayers(plr,args[1])) do
						if v.Character then
							for g,k in pairs(v.Character:children()) do
								if k:IsA("Pants") then k:Destroy() end
							end
							local pantsss = game:GetService("InsertService"):LoadAsset(args[2])
							if pantsss.Pants ~= nil then
								pantsss.Pants.Parent = v.Character
							end
						end
				end
			end
		};

**Comment by Sceleratis** [comment]
Yeah the next image lower *used* to be the texture for whatever the asset was, but that's not the case anymore. Anyone know if there's a good way to go about this? Are we able to just insert them via InsertService maybe (?)

**Comment by ChocoIate** [comment]
Yeah, I inserted the correct assets with InsertService:LoadAsset using the script above, and deleted whatever pants/shirt they had on originally

**Comment by joritochip** [comment]
This was fixed with commit https://github.com/Sceleratis/Adonis/commit/a2823ab68f77907e370cbcd424b1531dc50de224 .

**Comment by ccuser44** [comment]
Dr sceleratii you may close this issue
