### ISSUE TITLE
CustomRank admin level will return 0, disallowing kicking/banning regular players

### ISSUE THREAD

**Issue by TheEnvelope** [Sceleratis/Adonis#101]
![alt text](https://i.imgur.com/WmykOIp.png)

CustomRanks will always return 0, whereas normal players are also 0 so they can not kick or ban regular players.

Regular print = Individual who is given CustomRank attempting to kick
Warn = Target individual, who is a regular player

**Comment by NNickey** [comment]
Need to provide information on how you're applying custom ranks.

**Comment by TheEnvelope** [comment]
CustomRanks are applied through the settings module.

`settings.CustomRanks = {
		Government = {
			-- FIRESTONE
			"Group:2803360:150"; -- CCJ
			-- HOMELAND SECURITY
			"Group:2803370:100"; 
			-- STATE LEGISLATURE
			"Group:2840943:40"; -- SPT
			"Group:2840943:50"; -- PPT
			"Group:2840943:60"; -- PPT
			"Group:2840943:90"; -- LTGOV
			"Group:2840943:100"; -- GOV
			"GetEnveloped"
		}
	};
`

Then permissions are applied for the new CustomRank:

`settings.Permissions = {":s:Creators",":ls:Creators",":gear:Admins",":pm:Government",":n:Government",":m:Government",":h:Government",":setmessage:Government",":kick:Government",":ban:Government",":unban:Government",":tp:Government",":re:Government",":team:Government",":to:Government",":bring:Government",":logs:Government",':sm:Government',":cmds:Government",":admins:Government",":alert:Government",":notify:Government",":slock:Government",":unslock:Government",":shutdown:Government",":age:Government",":view:Government",":unview:Government",":track:Government",":untrack:Government",":refresh:Government",":chatlogs:Government"}`

**Comment by Sceleratis** [comment]
Ah so that's why that was happening.

**Comment by Sceleratis** [comment]
Just pushed an update. Should resolve this. Reopen if it doesn't.
