### ISSUE TITLE
Pressing "/" to use the custom chat results in "/" in the message box

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#102]
The same issue also happens with :bchat.

**Comment by TheEnvelope** [comment]
This can be fixed with `service.RunService.RenderStepped:Wait()` prior to `:CaptureFocus()`.

**Comment by P3tray** [comment]
@Sceleratis This was both fixed and later superceeded by privatechat.

Please close. 

![image](https://user-images.githubusercontent.com/31691973/128007182-01ba1df9-3634-408f-88ba-020c11db5914.png)
