### ISSUE TITLE
:thanos is completely broken

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#104]
It does not work with R6 or R15.
<img width="433" alt="Screen Shot 2020-04-19 at 10 29 49 am" src="https://user-images.githubusercontent.com/62996935/79676273-05280400-8229-11ea-97d2-2c0c7d8d70bc.png">

**Comment by Sceleratis** [comment]
Just tested it. Appears to work.

**Comment by ccuser44** [comment]
For me this does not work. The error is "Invalid argument #2 to random (interval is empty)" at the line of 9485.

**Comment by phoebe-leong** [comment]
https://github.com/Sceleratis/Adonis/issues/165

**Comment by Expertcoderz** [comment]
Yep, doesn't seem to work for me. Gives an error message mentioning 'interval is empty'.

**Comment by GalacticInspired** [comment]
![image](https://user-images.githubusercontent.com/73362346/118375749-f8a8e300-b5c3-11eb-9362-a1b2489fd394.png)

**Comment by chexburger** [comment]
Comes from https://github.com/Sceleratis/Adonis/blob/master/MainModule/Server/Commands/Fun.lua#L757

**Comment by Deniied** [comment]
If you remove the ``:`` from the title of this issue, you get emo thanos instead. Hope this helped!

**Comment by P3tray** [comment]
Since expertcoderz added labels, we need to make sure it's still broken two years later.

**Comment by Expertcoderz** [comment]
Investigation in progress.

**Comment by Expertcoderz** [comment]
"Interval is empty" errors involving ``math.random`` are generally caused by the second argument ``n`` to be smaller than the first argument ``m``, ex: ``math.random(1, 0) --> ERROR``.

However, this no longer seems to be an issue for the :thanos command after update(s) have been made to it, hence preventing the error from occurring.
