### ISSUE TITLE
Account age information from :info does not work if the player has not joined the server

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#105]
Account age information from :info does not work if the player has not joined the server. It stays at 0.
<img width="281" alt="Screen Shot 2020-04-19 at 2 01 55 pm" src="https://user-images.githubusercontent.com/62996935/79679157-b5f0cc00-8246-11ea-9af7-e421c599198e.png">

**Comment by Sceleratis** [comment]
I don't think there's a way to get the players age when they aren't in the server. It's just reading their AccountAge property.

**Comment by DraconicChris** [comment]
You could get the join date by using a proxy and the Roblox API. You could then convert this to an age. 

https://devforum.roblox.com/t/how-do-i-fetch-the-account-age-from-the-api/464984

Not sure where people'll get the proxy tho

**Comment by NNickey** [comment]
Seems overkill to involve a proxy for an manual command that's intended for
use on in-game players only.

**Comment by DraconicChris** [comment]
I definitely agree; I was just saying it was possible lol
