### ISSUE TITLE
:size command stopped working again

### ISSUE THREAD

**Issue by FlatOutGamer3000** [Sceleratis/Adonis#111]
![RobloxScreenShot20200503_191829350](https://user-images.githubusercontent.com/25018581/80928587-64326080-8d73-11ea-8b2c-e8b5b8e63a9a.png)

Yeah... Been trying to figure this out for a while. Could use a fix about now.

**Comment by moo1210** [comment]
Are you using R15? If so #13

**Comment by FlatOutGamer3000** [comment]
I tried using both R15 and R6, neither worked.

**Comment by moo1210** [comment]
This is most likely the same issue as issue 13 as it is unable to find Torso. However, R15 has a uppertorso and a lowertorso, R6 does not have this issue. Inless there's another reason why it cannot find your torso that I cannot think of.

**Comment by Sceleratis** [comment]
would bodyscale or whatever work for this cuz I'd rather just use that than some painful janky solution like what we have now

**Comment by NNickey** [comment]
yeah, would just go through all the values in humanoid for changing size
and multiply it by number

**Comment by Sceleratis** [comment]
just confirmed the scale stuff should work as a suitable replacement, updating it in now.

**Comment by Sceleratis** [comment]
Updated in the use of bodyscale values and removed the old code entirely. It works on R15, haven't tested anything else so I don't know if this works at all with R6.
