### ISSUE TITLE
Adonis Console breaks ROBLOX Chat GUI

### ISSUE THREAD

**Issue by Drflash55** [Sceleratis/Adonis#117]
When using the latest version of Adonis (Version 170), if you use the Console Key to bring up the console that's used for putting in commands to use on Adonis, the Chat GUI completely vanishes, and won't reappear when the console is closed.

Will show a GIF here of what happens so that I can show the issue more appropriately.

**Comment by NNickey** [comment]
Intentional, Adonis sets all core gui features off to show the console and it's available commands.

**Comment by Drflash55** [comment]
And yet, the chat won't show back up at all when it's closed, that's my point. I still need to get the GIF of this to show it off more appropriately.

**Comment by Drflash55** [comment]
This is what happens when using Adonis.

The chat works fine normally when you join the server, but when you open up the console and close it off, the chat GUI doesn't get restored, thus meaning you can't talk to other people anymore, as if you were muted.

![](https://thumbs.gfycat.com/ShadowyHonoredHagfish-size_restricted.gif)

**Comment by NNickey** [comment]
Any error in F9/Dev Console?

**Comment by Drflash55** [comment]
I'll give it a look-see to see what happens with it, the client console doesn't show anything, so I'll have to look at the server console.

**Comment by Drflash55** [comment]
I tested this out on my own place, and it doesn't break. If I'm gonna make a guess, it might be conflicting with "HD Admin Commands", which I'll also give a try as well.

**Comment by Drflash55** [comment]
![image](https://user-images.githubusercontent.com/13694448/83298295-2681f580-a1c2-11ea-84aa-457ca782f9b9.png)

As I thought, HD Admin Commands does conflict with Adonis with the new ROBLOX Gui.

**Comment by enescaglayan** [comment]
Does the issue still persist? not for me.

**Comment by Sceleratis** [comment]
Check if this is still an issue.

**Comment by enescglyn** [comment]
i cannot reproduce it

**Comment by enescglyn** [comment]
it also never happened in my life

**Comment by EnderUwU** [comment]
works for me
