### ISSUE TITLE
fr0g uses an invalid decal

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#12]
Current using: https://www.roblox.com/library/185945588/redirect
Should be using: https://www.roblox.com/library/185945586/frame-007

Stop using random people's assets!
lo
![image](https://user-images.githubusercontent.com/24907394/41043129-d8e8b00e-6968-11e8-8b4a-00fc736ee6a9.png)

**Comment by Sceleratis** [comment]
This was fixed when I merged ;p
