### ISSUE TITLE
How to be a adonis agent

### ISSUE THREAD

**Issue by enescglyn** [Sceleratis/Adonis#138]
hi when you run !agents you will get a gui with empty table, i was wondering if it is possible to be a agent ?

**Comment by Sceleratis** [comment]
Agents are users with access to specific monitor-only commands (as in, they can read logs n stuff but can't actually do anything like :kill)

Agents are a part of the Trello integration however I should probably move them to settings. Their role is basically to monitor a place for suspicious stuff and report it to admins.

**Comment by enescglyn** [comment]
is it possible to be one?
