### ISSUE TITLE
How to use :screenimage?

### ISSUE THREAD

**Issue by foili** [Sceleratis/Adonis#147]
:screenimage doesn't work for me. It only shows a black screen whenever I run it. I'm not sure if I'm doing this wrong, or this is a bug, that's why I'm posting it as a question.

**Comment by joritochip** [comment]
The usage for the screen image command is ":screenimage <player> <textureid>". For example, ":screenimage me 109251559" should put an Epic Face decal on your screen.

I tried using the command and it worked just fine for me, although it did display a black image for a short moment while the image loaded. Are you using an image that is deleted or transparent (and therefore wouldn't appear to show anything)?

**Comment by foili** [comment]
Thank you. I fixed the issue by putting the image on a brick in studio, then copying the decal from there. But I've noticed it isn't compatible with transparency—the transparent bits are black—is this a bug?

**Comment by Sceleratis** [comment]
It uses textures (the thing you grabbed in studio)

**Comment by foili** [comment]
Thank you! I'll be closing this thread now. But if it's possible, transparency should be compatible with this command. Thank you again.

**Comment by foili** [comment]
------------
