### ISSUE TITLE
Seats break in R6

### ISSUE THREAD

**Issue by NACA-FAS** [Sceleratis/Adonis#153]
I'm currently experiencing an issue in one of my games where Adonis seems to be affecting the operation of seats in forced R6. This issue started happening out of random, and I have narrowed it down to Adonis. The issue I'm facing is that when I go to use a seat with R6 forced, they won't allow you to sit. If I use the fling command to fling myself, they start working. Otherwise I've found making the game R15 (which I don't want) or removing Adonis completely fixes the issue.

**Comment by joritochip** [comment]
I've also found that this issue occurs when you use :fly regardless of if you are actually flying or not. Usually I have to do :unfly to be able to sit down again.

**Comment by NACA-FAS** [comment]
> I've also found that this issue occurs when you use :fly regardless of if you are actually flying or not. Usually I have to do :unfly to be able to sit down again.

Ay it's weird, but also not useful for some games. I've also found out another person has to do :sit then jump for them to work.. Ideally needs fixing soon to be honest

**Comment by NNickey** [comment]
Need's a repo. What settings do you have enabled?

**Comment by NACA-FAS** [comment]
> Need's a repo. What settings do you have enabled?

Default settings, only thing I've changed is the datastore name/ code

**Comment by NACA-FAS** [comment]
Just wondering if anyone knows if/when this'll be looked into? Quite the annoyance having the issue to be honest..

**Comment by ccuser44** [comment]
I have never observer this. However when using fly while in a seat might cause weird errors to occur. Tho this was in an older version of adonis.

**Comment by GalacticInspired** [comment]
Yes. This is a true bug. It is very annoying.

**Comment by Sceleratis** [comment]
Still an issue? I know we've had one or two updates involving seats and fly. If this is still an issue just reopen it. Closing for now to clear cruft.
