### ISSUE TITLE
:dance doesnt work

### ISSUE THREAD

**Issue by DaEnder** [Sceleratis/Adonis#165]
if you do :dance it removes your animation

**Comment by EnderUwU** [comment]
this also happes with :animation

**Comment by joritochip** [comment]
Are you using R6 or R15?

**Comment by TheLegendarySpark** [comment]
> Are you using R6 or R15?

``Humanoid:LoadAnimation(animation)`` is deprecated. The RigType isn't the issue unless the animation doesn't support a certain RigType.

**Comment by EnderUwU** [comment]
R15

**Comment by Sceleratis** [comment]
R15 and anthro breakin all the character specific stuff qq

**Comment by chexburger** [comment]
https://github.com/Sceleratis/Adonis/pull/388

**Comment by DavidBaszuckiA** [comment]
Good news! If you upgrade to Premium Adonis for 34.99 a month, you can now use :dance with R15

**Comment by GalacticInspired** [comment]
should be fixed?

**Comment by karl-police** [comment]
> should be fixed?

Yeah.
