### ISSUE TITLE
:bot doesn't work properly

### ISSUE THREAD

**Issue by Dylan56202** [Sceleratis/Adonis#175]
Using :bot does create bots but they do not walk. I did try "bot me 5 true" and they still will not walk. If I remember correctly this has been broken for a few weeks now. 

EDIT: This only happened in my game and I found the issue

**Comment by TheLegendarySpark** [comment]
I've tested the bot command and did exactly the same input as you. Fortunately, Adonis MainModule doesn't have any issues with the command. I'm suggesting that you add the newest additions from the latest to yours to ensure your module has the right fix.

**Comment by Dylan56202** [comment]
It must be something with my game then, I'll also double check the mainmodule. Thanks for taking a look anyway.

**Comment by Dylan56202** [comment]
Something in my game caused this, I fixed it and it works.
