### ISSUE TITLE
:uncharaudio (player) is broken

### ISSUE THREAD

**Issue by Dylan56202** [Sceleratis/Adonis#176]
:uncharaudio (player) does not get rid of the audio playing in a character. 
:charaudio (player) works fine however.

**Comment by TheLegendarySpark** [comment]
Gotcha! I found the issue with ``charaudio`` command. It didn't name the character audio sound as ``ADONIS_AUDIO``. Refer to https://github.com/Sceleratis/Adonis/pull/177/commits

**Comment by Dylan56202** [comment]
It's been fixed
