### ISSUE TITLE
:sm and :m is not working

### ISSUE THREAD

**Issue by alvinzzzzz** [Sceleratis/Adonis#185]
Everytime I do that command it will just pop up a unknown error.

**Comment by EnderUwU** [comment]
_the what__

**Comment by EnderUwU** [comment]
it works for me are you sure you are using real adonis by Davey_Bones?

**Comment by alvinzzzzz** [comment]
@EnderUwU I sure it is the real adonis from Davey_Bones here is a pic to show the error
![image](https://user-images.githubusercontent.com/64497526/99919574-15c6be00-2cd3-11eb-8884-210db5edb1b6.png)

**Comment by Sceleratis** [comment]
did you change the system message setting at all?

**Comment by alvinzzzzz** [comment]
@Sceleratis I never change the system message or the theme

**Comment by NNickey** [comment]
:scriptlogs

**Comment by alvinzzzzz** [comment]
@Sceleratis @NNickey 
![image](https://user-images.githubusercontent.com/64497526/100380443-b9fa7e80-2fcb-11eb-90dc-3aef23a9de14.png)

**Comment by NNickey** [comment]
Very recent message, scroll down, also show :errorlogs after running :sm and :m

**Comment by Sceleratis** [comment]
that cached method error is a little mysterious

**Comment by alvinzzzzz** [comment]
@NNickey @Sceleratis 
![image](https://user-images.githubusercontent.com/64497526/100387036-e1594780-2fdb-11eb-985f-f91322cfd72f.png)
![image](https://user-images.githubusercontent.com/64497526/100387067-f6ce7180-2fdb-11eb-826f-12fc379c362f.png)
for error log it show nothing           
![image](https://user-images.githubusercontent.com/64497526/100387095-0a79d800-2fdc-11eb-9aef-6020f7123288.png)

**Comment by Sceleratis** [comment]
can you also link the place?

**Comment by alvinzzzzz** [comment]
Oh yes @Sceleratis 
https://www.roblox.com/games/5980229588/testing-center-0?refPageId=f93a5f65-7199-42f4-ae69-21db8bd4cd17
here

**Comment by Sceleratis** [comment]
So, I'm at the place and currently testing as I type this. I am genuinely stumped. Anyway you could share the place file?

**Comment by Sceleratis** [comment]
Aight I fixed the stupid Unknown error thing. Apparently it's being caused by this:
![image](https://user-images.githubusercontent.com/18238620/100548806-de10c680-323c-11eb-891c-0eb424cadcea.png)
??????

**Comment by Sceleratis** [comment]
OH LOL 
![image](https://user-images.githubusercontent.com/18238620/100549106-fa156780-323e-11eb-86ad-0f46e9b64d84.png)

**Comment by Sceleratis** [comment]
ITS BREAKING CUZ THERES A PART IN PLAYERS LMAO

**Comment by Sceleratis** [comment]
Fixing now so it shouldn't do that

**Comment by alvinzzzzz** [comment]
@Sceleratis I just waked up and I have no idea why is there a part in player. Anyways thanks for fixing it :)
