### ISSUE TITLE
!sparkles and !fire colors not working for donor perks.

### ISSUE THREAD

**Issue by Zakalot** [Sceleratis/Adonis#187]
Basically, using them and then specifying a color does not work. It will always use white.

**Comment by Sceleratis** [comment]
Are you using brick colors with proper case? Eg. "Really red" and not "really red" or "red"

**Comment by EnderUwU** [comment]
https://developer.roblox.com/en-us/articles/BrickColor-Codes they are case sensitive

**Comment by Zakalot** [comment]
It worked, thanks! I was just dumb.
