### ISSUE TITLE
[Code Review needed] Dog command

### ISSUE THREAD

**Issue by TheLegendarySpark** [Sceleratis/Adonis#191]
A month ago, the dog command started working again. Unfortunately, it broke. I'm not quite intelligent to understand Motor6D CFrames. Any reasons?

https://github.com/Sceleratis/Adonis/pull/178/commits/c5bcc3be912445640729e38bf92ded4d1db2abd3

**Comment by Sceleratis** [comment]
Yeah that's strange. Were you maybe using R6 during that time?

**Comment by TheLegendarySpark** [comment]
R15 doesn't work, but the command only works for R6
