### ISSUE TITLE
Cape and invalid Material Enums

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#2]
![image](https://user-images.githubusercontent.com/24907394/40981074-b33eba5c-689f-11e8-8593-de4ed9fd50a3.png)

Check if the material being set is an actual material.
(Causes all clients to warn that whatever they set was an invalid Enum)

**Comment by pbstFusion** [comment]
Is this still an issue

**Comment by outersalemsim** [comment]
intercom

**Comment by Sceleratis** [comment]
.... uh was this ever fixed

**Comment by chexburger** [comment]
Persists as warning in the client.
![image](https://user-images.githubusercontent.com/15860911/124405876-02fe7800-dcfd-11eb-978b-bb79715cef0b.png)
