### ISSUE TITLE
clickwalk Uses hopperbins

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#20]
![image](https://user-images.githubusercontent.com/24907394/41049669-124d2088-6977-11e8-8139-e477ae9f9202.png)

oof

**Comment by ccuser44** [comment]
Hey scel or generalscripter this issue is fixed some1 close it.

**Comment by ccuser44** [comment]
@Sceleratis dis is fixed also so u can close the issue
