### ISSUE TITLE
Issue with commands inside of command bar

### ISSUE THREAD

**Issue by benjamins5320** [Sceleratis/Adonis#208]
Whenever you say a command with me inside of it like for example :fly me in the command barIt will say "Me is not a valid command."
Proof: https://user-images.githubusercontent.com/71562138/103161756-c711b580-47a3-11eb-868e-e04911606627.mov

**Comment by ccuser44** [comment]
I have had once an issue with :pban ning someone via the command bar buy chat worked. But that was on an old version of adonis.  

Are you sure you are using the newest version of adonis and are you sure that HD admin is not breaking something. Check is HD admin is the cause of the issue.

**Comment by joritochip** [comment]
Does the game this issue is occurring in have any plugins that modify functions related to running commands? Additionally, as the above comment said, make sure you are running the latest version of Adonis.

**Comment by benjamins5320** [comment]
Thank you for your help.
