### ISSUE TITLE
Update the github wiki to be up to date with https://developer.adonis.dev/

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis#238]
Make the wiki on the github to be up to date with the wiki on the adonis website. This : https://developer.adonis.dev/

**Comment by joritochip** [comment]
Alternatively the wiki should just be wiped and redirected to https://developer.adonis.dev/ instead.

**Comment by ccuser44** [comment]
Yeah. But I mean the wiki is usefull to have in github too.

**Comment by Sceleratis** [comment]
tbh the adonis wiki needs a lot of documentation still qq
