### ISSUE TITLE
Webpanel polls too often. Also trello does not respect settings.HttpWait

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis#240]
̶T̶h̶e̶ ̶w̶e̶b̶p̶a̶n̶e̶l̶ ̶p̶o̶l̶l̶s̶ ̶t̶o̶o̶ ̶o̶f̶t̶e̶n̶ ̶w̶h̶i̶c̶h̶ ̶m̶a̶y̶ ̶c̶a̶u̶s̶e̶ ̶t̶h̶e̶ ̶H̶t̶t̶p̶S̶e̶r̶v̶i̶c̶e̶ ̶t̶o̶ ̶g̶e̶t̶ ̶o̶v̶e̶r̶l̶o̶a̶d̶e̶d̶ ̶b̶y̶ ̶b̶e̶t̶t̶i̶n̶g̶ ̶o̶v̶e̶r̶ ̶t̶h̶e̶ ̶5̶0̶0̶ ̶r̶e̶q̶u̶e̶s̶t̶s̶ ̶p̶e̶r̶ ̶m̶i̶n̶u̶t̶e̶.̶
̶T̶h̶e̶ ̶d̶e̶l̶a̶y̶ ̶s̶h̶o̶u̶l̶d̶ ̶b̶e̶ ̶3̶ ̶s̶e̶c̶o̶n̶d̶s̶ ̶a̶n̶d̶ ̶n̶o̶t̶ ̶w̶a̶i̶t̶(̶)̶.̶ ̶w̶a̶i̶t̶(̶)̶ ̶i̶s̶ ̶t̶o̶o̶ ̶f̶a̶s̶t̶.̶ ̶I̶n̶s̶t̶e̶a̶d̶ ̶i̶t̶ ̶s̶h̶o̶u̶l̶d̶ ̶b̶e̶ ̶w̶a̶i̶t̶(̶3̶)̶ ̶o̶r̶ ̶w̶a̶i̶t̶(̶4̶)̶

Make the trello polling seperate from the webpanel polling so it can respect settings.HttpWait

Also because some games have many games servers and they all poll you could make it so only 1 server is polling and the others lisen to changes with MessagingService and coordinate the stuff trough a datastore. Then change the server which polls regularly for redundancy. And make it so that the trello and WebPanel check for changes and if they see no changes they will not fire the events and update any data.

**Comment by Cald-fan** [comment]
The webpanel uses long polling.

As for trello make it respect it yourself, idk what to tell you for that

**Comment by ccuser44** [comment]
Oh. But do you think it would be a good idea ot have just one server to be polling and then send changed data trough MessagingService?

**Comment by joritochip** [comment]
> Oh. But do you think it would be a good idea ot have just one server to be polling and then send changed data trough MessagingService?

Seems like that would be unnecessary. Assuming the panel is not being actively used by the game's creator, it is only sending one request per minute.

**Comment by ccuser44** [comment]
oki will make new issue about trello not respecting settings and will close this 1.

**Comment by ccuser44** [comment]
remade into #243
