### ISSUE TITLE
Make trello polling respect settings.HttpWait

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis#243]
Make the trello polling seperate from the webpanel polling so it can respect settings.HttpWait

Also because trello polling is sunced with webpanel it causes trello not to be updated if webpanel does not send data.

**Comment by Cald-fan** [comment]
There is nothing synced about the two. The panel uses long polling while trello runs based off the http wait setting. The webpanel does not use httpwait. I'm not sure what you are talking about but you can ask about it in the discord

**Comment by Cald-fan** [comment]
i misunderstood what you were saying, i made a pull request!

**Comment by ccuser44** [comment]
oki

**Comment by ccuser44** [comment]
This is not fixed still.

What I suggest should be done is remove any traces of the trello stuff from the webpanel because it is already being activated by
```
	--// Trello updater
	if server.Settings.Trello_Enabled then
		service.StartLoop("TRELLO_UPDATER",server.Settings.HttpWait,server.HTTP.Trello.Update,true)
	end
```


just remove this \/ from webpanel
```
			--// Trello Data
			if data.trello.board and data.trello["app-key"] and data.trello.token then
				server.Settings.Trello_Enabled = true
				server.Settings.Trello_Primary = data.trello.board
				server.Settings.Trello_AppKey = data.trello["app-key"]
				server.Settings.Trello_Token = data.trello.token

				server.HTTP.Trello.Update()
			end
```

**Comment by Cald-fan** [comment]
this was fixed a while ago just never closed
