### ISSUE TITLE
not working with hd admin please help

### ISSUE THREAD

**Issue by SkyeGamezYT** [Sceleratis/Adonis#245]
i want both admins in my game for more trolling fun but if I open the hd admin command bar it opens adonis is there any way to change the keybind or something?

**Comment by EnderUwU** [comment]
go to fucking settings and chanche it ez fix
also HD admin is a backdoor just saying

**Comment by moo1210** [comment]
@EnderUwU Let's not spread false information about HD admin being a backdoor.
You can change the command bar button two ways, (this way is easier) by going into :settings and scrolling down to ConsoleKeyCode then remap it. (This way is slightly harder if you don't understand the roblox keycode enum or how to edit values) Or by going to the settings modulescript inside the config folder in the explorer window inside roblox studio (if you don't understand how to do this I would recommend watching the first minute or two of the [official adonis quick start guide](https://youtu.be/XnhWcfoAJ_o)) At the line with `settings.ConsoleKeyCode` you should replace what's current inside the quotes (Quote) with a [Roblox keycode](https://developer.roblox.com/en-us/api-reference/enum/KeyCode),

**Comment by Sceleratis** [comment]
This isn't really an issue, and it's been answered sufficiently, so I'm just gonna close it.
