### ISSUE TITLE
locallog Refreshing a player's locallog when they leave/get kicked (Errors)

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#27]
![image](https://user-images.githubusercontent.com/24907394/41127089-592903e8-6a6f-11e8-86c3-3e64fc56e399.png)

Errors.

**Comment by Mudock-Yatho** [comment]
Still not fixed
![image](https://user-images.githubusercontent.com/24907394/41185339-ea8f0f2a-6b4c-11e8-941d-2fd23fdd9ae4.png)

**Comment by Mudock-Yatho** [comment]
![image](https://user-images.githubusercontent.com/24907394/41304826-d8186228-6e36-11e8-8c35-3deefc0f183b.png)
![image](https://user-images.githubusercontent.com/24907394/41304836-dcda1374-6e36-11e8-8122-74583e0b63cc.png)

Better hecc'in fix this already or reopen this issue.

**Comment by Sceleratis** [comment]
ugh what

**Comment by Sceleratis** [comment]
how bout now?
