### ISSUE TITLE
console errors sometimes when typing

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#28]
![image](https://user-images.githubusercontent.com/24907394/41128054-9fd6f978-6a72-11e8-8ac3-d39deb482514.png)

oof poor string match

**Comment by Sceleratis** [comment]
What's the splitkey set to and what message are you typing? It shouldn't be throwing this error...

**Comment by Mudock-Yatho** [comment]
![image](https://user-images.githubusercontent.com/24907394/41211689-92a6ae68-6cfe-11e8-8d2b-632254fa917b.png)
Literally type [ ] or [] and it errors.
