### ISSUE TITLE
Is it possible to make a command also run another command

### ISSUE THREAD

**Issue by Greymagic27** [Sceleratis/Adonis#292]
What I'm thinking is making the warn command for my game also show any warnings that user currently has. Is this something that's possible to do right now?

**Comment by pacucci** [comment]
Yes! 				Admin.RunCommand(Settings.Prefix.."commandname",arg1,arg2andsoon)

**Comment by Greymagic27** [comment]
Oo thanks! I'll forward that along to my dev team :)
