### ISSUE TITLE
Mass GetData Requests "Timed Out"

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#3]
![image](https://user-images.githubusercontent.com/24907394/40981178-f38013e0-689f-11e8-8d62-b83a4481f986.png)

Still happening, started awhile ago.

**Comment by Sceleratis** [comment]
Maybe I can make a queue type thing for it, but then that will cause problems with getting player's data on join... I could also store everything in one table and update it occasionally but there's a data limit so that wouldn't work for popular games... I guess maybe I could check when the last datastore call was and then just have it wait for a second if it's too soon maybe?

**Comment by Dog2puppy** [comment]
Why exactly is it timing out in the first place? The errors I get really don’t tell why.

**Comment by Sceleratis** [comment]
If I had to guess, multiple people are joining at the same time as that should be the only time it grabs a player's data from the datastore (it stores it in a table while they are in the server and never grabs it again unless they rejoin)

**Comment by Dog2puppy** [comment]
My game is always empty and when I join it still errors I think.

**Comment by Sceleratis** [comment]
That's strange then. Maybe something is going wrong on roblox's end?

**Comment by Dog2puppy** [comment]
Just checked and it didn’t error this time. Might’ve been something that errored some other time.

**Comment by Mudock-Yatho** [comment]
Roblox does limit the amount of requests that can be made in/out for remotes now, it's pretty high so you shouldn't be reaching it, but it might be possible.
However it did happen to me when I was in a server by myself.

**Comment by Dog2puppy** [comment]
@Mudock-Yatho I think this is a data store issue.

**Comment by Sceleratis** [comment]
o Wait I thought this was a datastore thing but it isn't, it's the remote event getdata timeout

![image](https://user-images.githubusercontent.com/18238620/41040965-dd9d5692-696b-11e8-932e-414dc53c4973.png)

**Comment by Mudock-Yatho** [comment]
![image](https://user-images.githubusercontent.com/24907394/41041196-12b58974-6964-11e8-9f44-352e8faa13d5.png)

**Comment by Sceleratis** [comment]
yeah I made a mistake when I added it lol

**Comment by Dog2puppy** [comment]
I’m so confused looking at the source of Adonis.
