### ISSUE TITLE
if two 'admins' run :m, the first command locks up and stays on screen

### ISSUE THREAD

**Issue by NNickey** [Sceleratis/Adonis#30]
majo bug, lemme find a solution wif a pull.

**Comment by NNickey** [comment]
Under UI.rbxm, Default, Message, Config, Code, add on line 24.

`service.Debris:AddItem(gui,tim+5 or 10)`

can help alleviate issues with messages staying on screen, so the message can at least disappear!

**Comment by Mudock-Yatho** [comment]
![image](https://user-images.githubusercontent.com/24907394/41185520-abeeb50c-6b4e-11e8-9916-67fa7ea6d5ff.png)
