### ISSUE TITLE
Export warnings

### ISSUE THREAD

**Issue by Greymagic27** [Sceleratis/Adonis#310]
Hi,

Is there any way I could export my warnings that I've given to an external database? Thinking of migrating my system over but I know everything is encrypted.

Additionally, is there any way to see the userIDs of anyone who's got a warning before?

**Comment by fxeP1** [comment]
> Hi,
> 
> Is there any way I could export my warnings that I've given to an external database? Thinking of migrating my system over but I know everything is encrypted.
> 
> Additionally, is there any way to see the userIDs of anyone who's got a warning before?


> Is there any way I could export my warnings that I've given to an external database?

Yes you can make sure you have these enabled and make sure to change the G_Access_Key to your own key.
![image](https://user-images.githubusercontent.com/64731916/114612766-719ddd80-9c9a-11eb-84a7-e07dad2ac59c.png)

Heres an example of using the G_API to access Core and adding a warning to ROBLOX with the Message "warning message".
```lua
-- Make sure to change TEST_LEY_EXAMPLE to your key.
local Core = _G.Adonis.Access("TEST_KEY_SAMPLE", "Core")

local PlayerData = Core.GetPlayer({userId = 1, UserId = 1})

--[[
	From -> The player who had warned them
	Message -> Warning message
	Time -> Epoch time for when they were warned.
]]

table.insert(PlayerData.Warnings, {From = "example_plr_name", Message = "warning message", Time = 0})
```

> Additionally, is there any way to see the userIDs of anyone who's got a warning before?

As of now Adonis isn't able to get a userids warnings but this plugin I made should work, make sure it is inside the Plugins folder.
![image](https://user-images.githubusercontent.com/64731916/114613339-1a4c3d00-9c9b-11eb-87f5-739fabd6966f.png)

Heres the source you should put inside the ModuleScript you make, It also needs to start with "Server: " to work.
```lua
--!nolint UnknownGlobal

local UserService = game:GetService("UserService")

return function()
	server.Commands.IdWarnings = {
		Prefix = server.Settings.Prefix;
		Commands = {"idwarnings", "idwarns"};
		Args = {"userid"};
		Description = "Shows warnings for userids";
		Hidden = false;
		Fun = false;
		AdminLevel = "Moderators";
		Function = function(plr,args)
			local PlayerData = server.Core.GetPlayer({userId = tonumber(args[1]), UserId = tonumber(args[1])})
			
			local PlayerName do
				local Success, ArrayResult = pcall(UserService.GetUserInfosByUserIdsAsync, UserService, {tonumber(args[1])})

				PlayerName = Success and ArrayResult[1].Username or "Unknown"
			end
			
			if PlayerData and typeof(PlayerData) == "table" then
				local WarningList = {}

				if PlayerData.Warnings then
					for k,m in pairs(PlayerData.Warnings) do
						table.insert(WarningList, {Text = "["..k.."] "..m.Message,Desc = "Given by: "..m.From.."; "..m.Message})
					end
				end

				server.Remote.MakeGui(plr, "List", {
					Title = PlayerName;
					Table = WarningList;
				})
			end
		end
	}
end
```

**Comment by Greymagic27** [comment]
Thanks, that's been super helpful! 

Do you know if there's a way to get every warning ever given?

**Comment by shnopy** [comment]
To access _G.Adonis you have to wait for adonis to finish initalising, if you're doing it from  a script add a wait for 12 seconds or so (Worked for me)

**Comment by DavidBaszuckiA** [comment]
Good news! If you upgrade to Premium Adonis for 34.99 a month, you can now automatically export warnings

**Comment by Deniied** [comment]
do the logservice

**Comment by joritochip** [comment]
As suggested above, you can use plugins to add commands that allow you to view warnings for a given ID. Additionally, newer DataStore methods such as [DataStore:ListKeysAsync()](https://developer.roblox.com/en-us/api-reference/function/DataStore/ListKeysAsync) and [DataStoreService:ListDataStoresAsync()](https://developer.roblox.com/en-us/api-reference/function/DataStoreService/ListDataStoresAsync) may be of more use to you if you'd like to export all warnings for all players.
