### ISSUE TITLE
A vulnerability.

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis#312]
The client can get the _G Access Key.

**Comment by p3tray** [comment]
How?

**Comment by ccuser44** [comment]
For some reason the client can request any setting (expect datastores and trello stuff) via client.Remote.Get("Setting",{"The setting index you want to get"})

**Comment by p3tray** [comment]
Well, this is interesting. Good job "harmful" _G settings are disabled by default in the settings.

**Comment by p3tray** [comment]
client.Remote.Get("AllSettings") returns all settings too.

**Comment by p3tray** [comment]
Good spot.

**Comment by TheLegendarySpark** [comment]
> client.Remote.Get("AllSettings") returns all settings too.

There's no vulnerability here. It's only accessible to Creators+

**Comment by TheLegendarySpark** [comment]
https://github.com/Sceleratis/Adonis/blob/b082023e766765ec843853a77193948101e528e5/MainModule/Server/Core/Remote.lua#L154

**Comment by Sceleratis** [comment]
The _G access key was also used for localscripts that needed to access client tables, though I think the majority of client related _G access stuff was disabled anyway so probably better to just blacklist it and maybe make a client specific key.

**Comment by ccuser44** [comment]
> Truthfully I'd like to remove _G.Access entirely

Removing the _G access API in my opinion isn't good as it still has it usecases.

But the client shouldn't really have access to some settings expecially the access key.

**Comment by Sceleratis** [comment]
I blacklisted the api key for the client in the most recent release. Closing this since it resolves the issue.
