### ISSUE TITLE
Did the renaming of Owners to HeadAdmins break anything

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis#315]
I am not sure if I am correct however if I are then backwards compatibility MUST BE ADDED!

**Comment by p3tray** [comment]
No it didn't. I still use a 2017 loader and everything works fine.

**Comment by ccuser44** [comment]
Ok going to close this soon if no issues are found

**Comment by ccuser44** [comment]
Ok it did not. I will close this.
