### ISSUE TITLE
Dex Error

### ISSUE THREAD

**Issue by TheMysticc** [Sceleratis/Adonis#324]
![image](https://user-images.githubusercontent.com/78848081/116762512-fc822480-aa5d-11eb-8064-9ede5ec633bc.png)

**Comment by Bjorn1504** [comment]
It has been broken for hell long, Hope this can be fixed.

**Comment by chexburger** [comment]
Resolved in https://github.com/Sceleratis/Adonis/commit/01013297e80c895d1c4c2c5c1b9407f2a0a929fa
