### ISSUE TITLE
ins Doesn't work with tools.

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#33]
![image](https://user-images.githubusercontent.com/24907394/41185938-a3ffa914-6b53-11e8-8cdd-cd5f5a378f21.png)

It should do `Object:IsA'Tool'or Object:IsA'HopperBin'` and parent it to the player's Backpack.

**Comment by Sceleratis** [comment]
I assumed all things inserted were inserted inside of a model....

**Comment by chexburger** [comment]
Tested and confirmed to work properly with tools.
