### ISSUE TITLE
Error: "Not running script because past shutdown deadline (x12)"

### ISSUE THREAD

**Issue by cassis163** [Sceleratis/Adonis#338]
The error is caused by running Adonis Loader in Roblox Studio. This is the code that is responsible (in Loader.server.lua):
```lua
if response == "SUCCESS" then
		if (data.Settings and data.Settings.HideScript) and not data.DebugMode then
			model.Parent = nil
			game:BindToClose(function()
				model.Parent = game:GetService("ServerScriptService")
				model.Name = "Adonis_Loader"
			end)
		end
		model.Name = "Adonis_Loader"
	else
```
DataModel:BindToClose should not be called from Roblox Studio (see https://developer.roblox.com/en-us/api-reference/function/DataModel/BindToClose).

**Comment by happyman090** [comment]
That's odd given I have had no issues with Adonis running in Roblox Studio. I have never seen an error similar to that before, except if I exit Play Solo before it has a chance to load properly.

**Comment by Sceleratis** [comment]
Someone had the same error appear on the discord (unless that was you?) but I personally have not encountered it yet.

**Comment by cassis163** [comment]
That was not me on Discord. I had to disable the loader in Roblox Studio with:
```lua
RunService:IsStudio()
```
I am not sure what causes it to break though. My best guess is that the place I am hired to fix dates from 2019, when this bug 'https://devforum.roblox.com/t/bindtoclose-100-infinite-yield/170469' was a thing.

**Comment by Sceleratis** [comment]
Gonna see what I can do about this now.

**Comment by fxeP1** [comment]
Its probably because when you stop a local GameServer it ignores `BindToClose` from yielding as it forces the server to close.
