### ISSUE TITLE
:viewlist is not working

### ISSUE THREAD

**Issue by Kim123LP** [Sceleratis/Adonis#344]
Following error at executing :viewlist

![image](https://user-images.githubusercontent.com/40537673/118336197-78c24080-b511-11eb-90fb-5076f6b84cf4.png)

**Comment by Sceleratis** [comment]
Check if this is still an issue on 218.4 (currently live)

**Comment by GalacticInspired** [comment]
This is still happening.

**Comment by Kim123LP** [comment]
This is still happening.

**Comment by GalacticInspired** [comment]
did you copy and paste my comment

**Comment by Kim123LP** [comment]
@Sceleratis Fix in https://github.com/Sceleratis/Adonis/blob/master/MainModule/Server/Dependencies/TrelloAPI.lua the capital/similar letters
