### ISSUE TITLE
hint Errors sometimes upon removal

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#35]
![image](https://user-images.githubusercontent.com/24907394/41205746-f357bb52-6cbe-11e8-99f5-8fbf9684b140.png)

the HECC why Remove

**Comment by Mudock-Yatho** [comment]
![image](https://user-images.githubusercontent.com/24907394/41206609-25e80182-6ccc-11e8-9cc6-8dc138cca693.png)

Happened when using :music

**Comment by Mudock-Yatho** [comment]
![image](https://user-images.githubusercontent.com/24907394/41211601-07e48200-6cfe-11e8-98ff-6811fb2a2542.png)

Happened during :music again.

**Comment by Sceleratis** [comment]
This is probably fixed
