### ISSUE TITLE
Cannot search in :tools gui

### ISSUE THREAD

**Issue by TheCakeChicken** [Sceleratis/Adonis#36]
![image](https://user-images.githubusercontent.com/33702174/41253976-e6444f60-6db9-11e8-936e-04cf7027647c.png)
You cannot search in the :tools gui, it's not directly an issue, but it's inconvenient in places with lots of tools.

**Comment by NNickey** [comment]
Would be nice if tools would also list all the tools the player currently has?

**Comment by TheCakeChicken** [comment]
No, there's a :viewtools command specifically for that. The :tools gui just shows ones that can be given to the player using :give

**Comment by Sceleratis** [comment]
I'll think about adding a search to it, currently there isn't one because the code for the gui isn't in its own module, instead it's sent from the server (in the command function) over to the client as a list of things to generate and the events to attach to them for the window gui.
