### ISSUE TITLE
[UI] Scaling and offsetting.

### ISSUE THREAD

**Issue by thatrelevantperson** [Sceleratis/Adonis#368]
Adonis has a long way to go with UI, but *may* be easily fixed with custom themes.
This is one issue: 
![image](https://user-images.githubusercontent.com/48195288/121944927-11620100-cd08-11eb-8e96-665f8819cd1b.png)

Text does not wrap in the gui and it overflows regardless the size.
A possible recommended fix:
- Set Anchor X to 1
- Position Scale X to 1

The two steps above ensure that the label stays to the right of the ui. It also seems that the fields are at a fixed size, so it leaves big space between the title and the actual input area when the window is sized. I do believe that anywhere in the area should be clickable instead of directly at the text.

![image](https://user-images.githubusercontent.com/48195288/121945378-9220fd00-cd08-11eb-9f4d-520a6cd5289c.png)

I would be doing these fixes myself, but I don't know my way around Adonis's core so I'm suggesting some fixes myself for anyone to implement themselves.

**Comment by thatrelevantperson** [comment]
There's also the listing (command list), it isn't in alphabetical order.

**Comment by LolloDev5123** [comment]
Comment written to revive Issue.

**Comment by joritochip** [comment]
Closing this issue because I don't think it is something we will consider implementing in Adonis 1.0. Development has begun on Adonis 2.0, where UI flexibility and scalability are being kept in mind during the design stages.
