### ISSUE TITLE
Error while running module UserPanel (Client)

### ISSUE THREAD

**Issue by chexburger** [Sceleratis/Adonis#387]
https://github.com/Sceleratis/Adonis/blob/867bf2ddf9947ff892e980fd1e6691607ce31a7a/MainModule/Client/UI/Default/UserPanel.lua#L222
![image](https://user-images.githubusercontent.com/15860911/124370369-185b9f80-dc34-11eb-991a-ef29754dd3f6.png)

Produced while trying to reproduce #339. Could not reproduce in new servers. Outputted to client console.
Active theme is BasicAdmin.

**Comment by chexburger** [comment]
Encountered only in a single server. Could not reproduce with same similar steps.

Steps I followed:

1. Change theme to BasicAdmin
2. Rejoin
3. Attempt to click help (this is where the error was)
2. Rejoin
3. Attempt to click help (same server, same issue)
4. Rejoin another server
3. Change theme to any other theme
4. Rejoin
5. Change theme to BasicAdmin
6. Rejoin
7. Attempt to click help (different server, no issue)
8. Repeat 3-7, same result

**Comment by DavidBaszuckiA** [comment]
Trello is not a database. Thanks.

**Comment by GalacticInspired** [comment]
Whoops, you forgot to switch accounts skid.

**Comment by DavidBaszuckiA** [comment]
![image](https://user-images.githubusercontent.com/86933176/124400901-64cadc00-dd15-11eb-8b95-77afcabade3c.png)

**Comment by DaEnder** [comment]
lol

**Comment by GalacticInspired** [comment]
Nice inspect element, I wonder where the Contributor tag went..

**Comment by DaEnder** [comment]
david join the discord lol https://discord.gg/aB7nXPP5

**Comment by chexburger** [comment]
> Trello is not a database. Thanks.

Trello isn't what's being addressed here tho so don't bother bringing it up. I'm well aware that Trello isn't a database.
Some people gotta expand their skillset of not shitposting on things.

**Comment by DavidBaszuckiA** [comment]
BasicAdmin is not Adonis. Please contact TheFurryFish for assistance. Thanks.
~ Bob Ross, Senior Adonis Support Specialist

**Comment by chexburger** [comment]
> BasicAdmin is not Adonis. Please contact TheFurryFish for assistance. Thanks.
> ~ Bob Ross, Senior Adonis Support Specialist

Almost like BasicAdmin is one of the Adonis themes stoopid

**Comment by DavidBaszuckiA** [comment]
We'll have to rename that ASAP for copyright.

**Comment by LolloDev5123** [comment]
oh stfu

**Comment by GalacticInspired** [comment]
Wow, David Baszucki is Adonis Customer Support Agent Senior wow

**Comment by Sceleratis** [comment]
Welp that's blocked now. Lol.

**Comment by GalacticInspired** [comment]
is there a way to give some people access to block

**Comment by LolloDev5123** [comment]
Comment written to revive Issue: Actual Issue.

**Comment by P3tray** [comment]
You know the rules, and so do I.

**Comment by DaEnder** [comment]
I forgor the rules 💀

**Comment by Deniied** [comment]
If my dad had wheels, he wouldn't be a bike. Because he's dead.

**Comment by P3tray** [comment]
Can this be closed now?
