### ISSUE TITLE
Control contributors behavior to not feed trolls

### ISSUE THREAD

**Issue by DavidBaszuckiA** [Sceleratis/Adonis#392]
After an experiment, we have found that you all feed trolls too much. This includes:

- Making another account that is supposedly me and saying racial slurs (terrible idea and extremely stupid, kindly don't do that)
- Replying way too much with nonsense.

I have a simple solution to all your problems. Shut up and ignore the trolls. Especially the guy saying racial slurs. Thanks.

**Comment by LolloDev5123** [comment]
nice one skid, not funny 
(tips: https://ifunny.co/)

**Comment by DavidBaszuckiA** [comment]
Thanks for the link! Unfortunately, yet again, you failed. This is no skid, no v3rm user, no troll. This is research, which yielded terrible results.

**Comment by LolloDev5123** [comment]
> Thanks for the link! Unfortunately, yet again, you failed. This is no skid, no v3rm user, no troll. This is research, which yielded terrible results.

Identify yourself ##gg#

**Comment by DavidBaszuckiA** [comment]
Well, considering the fact you said that word, maybe your connected to @DavidBaszuckiB

**Comment by LolloDev5123** [comment]
Ah stfu

**Comment by Expertcoderz** [comment]
Hello, nice research, but I request that you identify yourself.

**Comment by Sceleratis** [comment]
Going to ask you all to KINDLY STOP REPLYING TO STUPID STUFF.

All you're doing is creating further spam, which is not what issue discussions are for. Just message me on the Discord when they appear and I'll block/remove them.
