### ISSUE TITLE
Adonis unadmins Trello admins after rate limit

### ISSUE THREAD

**Issue by chexburger** [Sceleratis/Adonis#398]
Users on Trello are now unadmined if Trello is rate limited. Previous behavior was it would keep whatever it had successfully gotten and overwrite that the next time it successfully gets something rather than resetting it each time.

![image](https://user-images.githubusercontent.com/15860911/124692808-7dfd9500-de9b-11eb-912b-9a18832efcc8.png)
The command bar displays commands I had access to when spawning. The :admins list was pulled up when I had admin, and the error is after Trello has gotten rate limited.

**Comment by chasegolem** [comment]
Having this issue too, it also will reset the permissions to default when ratelimit reached.

**Comment by coasterteam** [comment]
The amount of requests a server makes per trello cycle has been reduced to 1 per board. 
While this bug is not directly fixed, it should be less common to appear.

**Comment by Deniied** [comment]
Maybe try not using trello and use a group like a normal person until the bug is fixed if you wanna use trello that bad?

**Comment by coasterteam** [comment]
> Maybe try not using trello and use a group like a normal person until the bug is fixed if you wanna use trello that bad?

or even better, firebase because trello isn't a database

**Comment by Deniied** [comment]
> > Maybe try not using trello and use a group like a normal person until the bug is fixed if you wanna use trello that bad?
> 
> or even better, firebase because trello isn't a database

Does Adonis have support for Firebase? Also why not just use a fucking mysql if you wanna use a database?

**Comment by CommodoreGamer118** [comment]
I honeslty see Firebase a more user-friendly option for users that wanna leave Trello behind, and supporting Firebase is kinda simple as of now, in my Adonis fork I added FB support myself since Trello was giving too many issues for me.

**Comment by joritochip** [comment]
This should be fixed by 5ae7a73.

**Comment by P3tray** [comment]
HAIL THE ALL MIGHTY JORITOCHIP!!! ALL HAIL!!
