### ISSUE TITLE
Nuke spams errors

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#4]
![image](https://user-images.githubusercontent.com/24907394/40981243-15af6182-68a0-11e8-8620-842778700835.png)

Correctly set Explosion.ExplosionType to something that doesn't interact with terrain and buildings.

**Comment by Mudock-Yatho** [comment]
The errors also happen on the server, as well as, all clients.

**Comment by Sceleratis** [comment]
O what would be a good explosion type to use then?

**Comment by Mudock-Yatho** [comment]
`Explosion.ExplosionType=Enum.ExplosionType.NoCraters`
(No craters for those that don't want huge gaping holes in their terrain that destroy their map, as well as, fixing errors caused by terrain/objects that can't be destroyed by explosions and cause errors.)
