### ISSUE TITLE
Allow `servers` to be refreshable

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#42]
![image](https://user-images.githubusercontent.com/24907394/41326052-cebfa62c-6e82-11e8-895f-d93084ab6f42.png)

Can't see any new servers I add or any servers I delete.
(Also maybe a command to :wipeservers or something, sometimes when testing new things I hop from server to server really fast to fix and test bugs real-time.)

**Comment by p3tray** [comment]
This was Fixed a year ago. It should now be closed. @Sceleratis
