### ISSUE TITLE
vote Using vote multiple times in succession causes the last vote to not work and error

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#45]
![image](https://user-images.githubusercontent.com/24907394/41430152-ddad5e9c-6fd4-11e8-99e9-cfbe1b5c0502.png)

oof my players

**Comment by chexburger** [comment]
Persistent issue.
![image](https://user-images.githubusercontent.com/15860911/124406439-9f754a00-dcfe-11eb-9a24-ac22e05983ec.png)

Only created 1 vote prompt, created warnings for other two.
![image](https://user-images.githubusercontent.com/15860911/124406468-aef49300-dcfe-11eb-8029-69ec853d3bb4.png)

**Comment by LolloDev5123** [comment]
Bump

**Comment by LolloDev5123** [comment]
Bump Again sorry ;)

**Comment by LolloDev5123** [comment]
Was this fixed?

**Comment by pbstFusion** [comment]
Dunno, maybe

**Comment by LolloDev5123** [comment]
We need to hunt these 21 issues down, we can't have open fixed issues as that might cause issues for non-weeb contributors.

**Comment by LolloDev5123** [comment]
AEIOUY

**Comment by P3tray** [comment]
oiasudoiuoidasuoid

**Comment by LolloDev5123** [comment]
Bruh 4 year old issue

**Comment by Expertcoderz** [comment]
Closing this once I confirm it's no longer an issue.

**Comment by Expertcoderz** [comment]
Alright, I've finally [fixed](https://github.com/Sceleratis/Adonis/commit/83115e095dbf9539ccaefa3c8dac8a2e19a72d3b) this issue after ~3.5 years by deleting one (1) line of code that caused the clientside Vote UI window to only support one instance at a given time (ie. AllowMultiple was incorrectly disabled).

**Comment by LolloDev5123** [comment]
Amen.
