### ISSUE TITLE
Severe Lag on Player Join in Certain Games

### ISSUE THREAD

**Issue by ChocoIate** [Sceleratis/Adonis#456]
As stated, there is severe join lag in certain games that I've pinpointed to the Adonis model. When disabled, this join lag does not occur, but enabling the model causes the join lag to reappear.

**Comment by fxeP1** [comment]
What type of lag are you experiencing, is this clientsided lag or is this serversided?

**Comment by Sceleratis** [comment]
I'm thinking it could be either the process of tossing the client into PlayerGui, or something with the datastore when it gets their data for the first time.

**Comment by ChocoIate** [comment]
Here's a link to the game:
https://www.roblox.com/games/6733267077/O-Obby-Superstar?
And severe server sided lag occurs which spikes every player in the game when players join.

**Comment by Sceleratis** [comment]
> 
> 
> Here's a link to the game:
> https://www.roblox.com/games/6733267077/O-Obby-Superstar?
> And severe server sided lag occurs which spikes every player in the game when players join.

Non-public game. Can't join to test/check stuff (like the version number and all that)

**Comment by ChocoIate** [comment]
Hey, so I did some testing on my own, and the lag is directly linked to the datastore from the admin. Disabling the datastore in the settings page of the admin completely fixed the issue.

**Comment by Sceleratis** [comment]
> 
> 
> Hey, so I did some testing on my own, and the lag is directly linked to the datastore from the admin. Disabling the datastore in the settings page of the admin completely fixed the issue.

I figured as much. I need to figure out an alternative way to go about player data.
