### ISSUE TITLE
Adonis Client using pcall on nil function

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#46]
![image](https://user-images.githubusercontent.com/24907394/41489156-8a835b3c-70b4-11e8-83b2-012e23154295.png)

what even?!?!?!

**Comment by Sceleratis** [comment]
Wtf that shouldn't be happening lol

**Comment by Sceleratis** [comment]
oh uh I haven;t seen this and it's been over a year soooooo ;)
