### ISSUE TITLE
F3X

### ISSUE THREAD

**Issue by xJustBen** [Sceleratis/Adonis#466]
The F3X model is very outdated, and would be nice if it had some type of auto update thing maybe, or just manually update it.

**Comment by fxeP1** [comment]
> The F3X model is very outdated, and would be nice if it had some type of auto update thing maybe, or just manually update it.

You could update the F3X deps yourself but i'm pretty sure it autoupdates for you (AutomaticUpdating script).

**Comment by xJustBen** [comment]
> > The F3X model is very outdated, and would be nice if it had some type of auto update thing maybe, or just manually update it.
> 
> You could update the F3X deps yourself but i'm pretty sure it autoupdates for you (AutomaticUpdating script).

---

The HD admin F3X model is updated every now and then where as adoni's is outdated and has bugs.

**Comment by fxeP1** [comment]
> > > The F3X model is very outdated, and would be nice if it had some type of auto update thing maybe, or just manually update it.
> > 
> > 
> > You could update the F3X deps yourself but i'm pretty sure it autoupdates for you (AutomaticUpdating script).
> 
> The HD admin F3X model is updated every now and then where as adoni's is outdated and has bugs.

PR has been made to update F3X to its latest version, Here it is: https://github.com/Sceleratis/Adonis/pull/462
Also some fixes with the GripPos on the Tool Instance being created.
