### ISSUE TITLE
Adonis can use a new ScreenGui setting to keep gui's on screen after respawn.

### ISSUE THREAD

**Issue by NNickey** [Sceleratis/Adonis#48]
http://wiki.roblox.com/index.php?title=API:Class/LayerCollector/ResetOnSpawn

**Comment by Sceleratis** [comment]
Yeah I know about this, and was going to use it, but haven't fully upgraded over to it yet (I think I changed it for certain guis but haven't actually done much code related stuff to kill the keepalive stuff)
