### ISSUE TITLE
Adonis Client -> Core -> Service -> UIS attempts to resume a non-suspended coroutine

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#49]
![image](https://user-images.githubusercontent.com/24907394/41738273-34eb43b8-7557-11e8-85e1-e18b9537f8dc.png)

Probably from a key bind but I'm not sure.
Player commands are disabled too so derp.

**Comment by Sceleratis** [comment]
Not sure what the cause it. Haven't seen it happening in testing so closing for now.
