### ISSUE TITLE
Adonis randomly kicks players (Or shutdowns, unconfirmed)

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#5]
![image](https://user-images.githubusercontent.com/24907394/40987436-2037f3cc-68ae-11e8-9fbe-970113d41cf1.png)
^ Client
v Server
![image](https://user-images.githubusercontent.com/24907394/40987452-2cbeeb0a-68ae-11e8-8b89-884eb1435622.png)

Unconfirmed if it's kicking/shutdowns the entire server or if it's limited to the client.

EDIT: Found another server error through my website logs.
![image](https://user-images.githubusercontent.com/24907394/40987551-63c89470-68ae-11e8-8003-1cc69ff12538.png)

**Comment by GalacticInspired** [comment]
Any update on this?

**Comment by DavidBaszuckiA** [comment]
Will give you the script for 1 million dollars.
