### ISSUE TITLE
Adonis Private Messages Not Working

### ISSUE THREAD

**Issue by jonahxo** [Sceleratis/Adonis#525]
Private messages are sent to the user(s), however, if they reply, the original sender will not receive the new message.

Steps to replicate:

- PM a user.
- Reply to the PM with anything.
- The reply won't come through.

I have attached a video below, from an alternative account.

https://user-images.githubusercontent.com/92191608/136638710-4bcc81d5-6e94-4db6-bcc1-6015c3f13d08.mp4

**Comment by LolloDev5123** [comment]
Are you using the v229 snapshot? I believe this has something to do with my RegEx filter, that detects blank/empty messages, but Im not sure.

**Comment by jonahxo** [comment]
> Are you using the v229 snapshot? I believe this has something to do with my RegEx filter, that detects blank/empty messages, but Im not sure.

I'm using the latest version of Adonis, yes.

**Comment by joritochip** [comment]
Should now be fixed with #529

**Comment by jonahxo** [comment]
> Should now be fixed with #529

Thanks so much. :)
