### ISSUE TITLE
Adonis Dex only changes a object once

### ISSUE THREAD

**Issue by GalacticInspired** [Sceleratis/Adonis#530]
When using dex, let's say changing a value, it only does it once to the server.

**Comment by GalacticInspired** [comment]
Let’s say you have a value. You change the value and it changes on the server. When changing it again, it changes locally in the dex, but server doesn’t trigger.

**Comment by P3tray** [comment]
Has there been any update on this, and will anyone make this change?

**Comment by moo1210** [comment]
Was unable to reproduce this a while ago when I was going to fix it in a dex update. Nor have I had it happen the many times I've used dex in-game recently.

**Comment by GalacticInspired** [comment]
> Was unable to reproduce this a while ago when I was going to fix it in a dex update. Nor have I had it happen the many times I've used dex in-game recently.

You sure?

https://user-images.githubusercontent.com/73362346/153626994-5cb78f9c-ad60-40ab-9080-76098aad03ed.mp4

**Comment by moo1210** [comment]
Still unable to reproduce this, even with a script in the workspace.

**Comment by joritochip** [comment]
I managed to replicate this, but only with a Script in the workspace. I'll look into this soon

**Comment by GalacticInspired** [comment]
Unable to re-enable the script after it was disabled with dex.

**Comment by GalacticInspired** [comment]
how do i reopen because there still issue

**Comment by joritochip** [comment]
Fix is on master branch, not release yet

**Comment by GalacticInspired** [comment]
epicly fixed now
