### ISSUE TITLE
Any documentation on the _G.Adonis variable?

### ISSUE THREAD

**Issue by Deniied** [Sceleratis/Adonis#542]
I'm looking for documentation for _G.Adonis, but I don't see anything for it. It could just be me being blind but is there anything?

**Comment by GalacticInspired** [comment]
Wont give it to you. Why should we help someone back door games? Don’t pretend that I don’t know who you are.

whoever is reading this wanting to help, don’t. You will make things more worse.

**Comment by GalacticInspired** [comment]
There is no reason for you to really know the _G api, don’t you think that it’s kinda suspicious?

**Comment by DaEnder** [comment]
only thing it can really do is make messages and hints

**Comment by Deniied** [comment]
> only thing it can really do is make messages and hints

Alright

**Comment by whymymousemoveonitsown** [comment]
Documentation: https://github.com/Sceleratis/Adonis/blob/1f19b5cd65ec88e8af1ae396fdaed4a802387cc1/MainModule/Server/Core/Core.lua#L1109

**Comment by Deniied** [comment]
> Documentation:
> 
> https://github.com/Sceleratis/Adonis/blob/1f19b5cd65ec88e8af1ae396fdaed4a802387cc1/MainModule/Server/Core/Core.lua#L1109

Thanks very much!

**Comment by Deniied** [comment]
> Wont give it to you. Why should we help someone back door games? Don’t pretend that I don’t know who you are.
> 
> whoever is reading this wanting to help, don’t. You will make things more worse.

It's funny how you think I'm going to use a serversided global variable to backdoor games from the client

![bruh](https://c.tenor.com/q3u8fU_Et88AAAAd/what.gif)

**Comment by ccuser44** [comment]
Also the client side _G api has more stuff

**Comment by ccuser44** [comment]
The _G api isnt properly documented or has any uniform way of functioning like mostvof the Service.lua code


Honestly a lot of code base reforms should be done including removal of fenvs.
