### ISSUE TITLE
Question about main module

### ISSUE THREAD

**Issue by gmoddev** [Sceleratis/Adonis#543]
So at line 41 in Server > Server why do you define a bunch of functions over again?
`local _G, game, script, getfenv, setfenv, workspace,
getmetatable, setmetatable, loadstring, coroutine,
rawequal, typeof, print, math, warn, error,  pcall,
xpcall, select, rawset, rawget, ipairs, pairs,
next, Rect, Axes, os, time, Faces, unpack, string, Color3,
newproxy, tostring, tonumber, Instance, TweenInfo, BrickColor,
NumberRange, ColorSequence, NumberSequence, ColorSequenceKeypoint,
NumberSequenceKeypoint, PhysicalProperties, Region3int16,
Vector3int16, elapsedTime, require, table, type, wait,
Enum, UDim, UDim2, Vector2, Vector3, Region3, CFrame, Ray, spawn, delay, task =
	_G, game, script, getfenv, setfenv, workspace,
	getmetatable, setmetatable, loadstring, coroutine,
	rawequal, typeof, print, math, warn, error,  pcall,
	xpcall, select, rawset, rawget, ipairs, pairs,
	next, Rect, Axes, os, time, Faces, unpack, string, Color3,
	newproxy, tostring, tonumber, Instance, TweenInfo, BrickColor,
	NumberRange, ColorSequence, NumberSequence, ColorSequenceKeypoint,
	NumberSequenceKeypoint, PhysicalProperties, Region3int16,
	Vector3int16, elapsedTime, require, table, type, task.wait,
	Enum, UDim, UDim2, Vector2, Vector3, Region3, CFrame, Ray, task.defer, task.delay, task;
`

**Comment by moo1210** [comment]
This is just loading globals instead of fetching them when there first executed, making the script not have (pretty minor in real-world use) slow downs while in use. In practice, this is [already built into Luau](https://luau-lang.org/performance#importing-global-access-chains), however getfenv/setfenv is used in Adonis so the built-in optimization is disabled.

**Comment by Sceleratis** [comment]
> This is just loading globals instead of fetching them when there first executed, making the script not have (pretty minor in real-world use) slow downs while in use. In practice, this is [already built into Luau](https://luau-lang.org/performance#importing-global-access-chains), however getfenv/setfenv is used in Adonis so the built-in optimization is disabled.

This is only part of it. The real reason is this was originally done in the client to prevent changes to global variables trickling in to the client. It was also done on the server just for the sake of consistency (and the very slight potential of better performance, but more so the first thing)

**Comment by Sceleratis** [comment]
But yeah I really need to get rid of setfenv usage as much as possible so we get those juicy optimizations.

**Comment by P3tray** [comment]
The question has been answered.
