### ISSUE TITLE
Any Adonis windows will not scale 

### ISSUE THREAD

**Issue by minimiscus** [Sceleratis/Adonis#545]
For some reason when I drag the edges, it does not scale the window.

https://user-images.githubusercontent.com/32967077/140797234-9aeee9f8-5b1e-40b5-bb2d-0b5e17aba02e.mp4

**Comment by fxeP1** [comment]
Are you able to provide an F9 log and possibly some specs (like monitor etc) with this too?

**Comment by P3tray** [comment]
Can this be closed now as nothing has happened?
