### ISSUE TITLE
[Rounded theme] Visibility issues with textlabels in tool list and color list UIs

### ISSUE THREAD

**Issue by Expertcoderz** [Sceleratis/Adonis#546]
![image](https://user-images.githubusercontent.com/81153405/141087480-b79a4f24-91ac-4c24-a9d2-6d06f83e7d2b.png)

(I made the color list UI based off the tools list so yes it inherits the problem:)
![image](https://user-images.githubusercontent.com/81153405/141087439-46e26639-bcd5-4a81-9d3a-8ddc7730b658.png)

**Comment by Deniied** [comment]
Maybe use Aero (The more superior theme) instead?

**Comment by Expertcoderz** [comment]
> Maybe use Aero (The more superior theme) instead?

~~I made Aero, of course it's more superior.~~

**Comment by CommodoreGamer118** [comment]
made a PR to fix these issues
https://github.com/Sceleratis/Adonis/pull/592
