### ISSUE TITLE
:shirt command is gone entirely.

### ISSUE THREAD

**Issue by MelonHeadzzz** [Sceleratis/Adonis#564]
Pretty self-explanatory, the shirt command has completely gone from :cmds, which is very necessary for our kinds of roleplay games.

**Comment by coasterteam** [comment]
Thanks! We're looking into it, expect the next release to have a fix for this issue

**Comment by moo1210** [comment]
Also, as a temporary workaround, you can still use the "giveshirt" alias.

**Comment by karl-police** [comment]
This has already been fixed.
