### ISSUE TITLE
Question: What is the purpose of this check

### ISSUE THREAD

**Issue by gmoddev** [Sceleratis/Adonis#569]
So I was snooping around in Core > Admin and on the IsPlaceOwner function on line 503, there is a check that checks if the player userid is -1, is there a purpose, if so what?

**Comment by Expertcoderz** [comment]
I guess it's to account for emulated players during Studio multi-client testing? Not very sure, though.

**Comment by Sceleratis** [comment]
> I guess it's to account for emulated players during Studio multi-client testing? Not very sure, though.

This. It makes it so "Player1" when testing in studio is seen as the place owner.
