### ISSUE TITLE
Webpanel Question:

### ISSUE THREAD

**Issue by gmoddev** [Sceleratis/Adonis#572]
Is it possible to find the source of the webpanel and possibly set it up on my own domain so im able to allow multiple people to access the webpanel?

**Comment by coasterteam** [comment]
This would be a question for @Cald-fan

**Comment by P3tray** [comment]
> Is it possible to find the source of the webpanel and possibly set it up on my own domain so im able to allow multiple people to access the webpanel?

The source for the web panel (inside Adonis) is in the GitHub repository, but the website source isn't and will never be so.

See MainModule > Server > Dependencies > WebPanel.lua

It's a good starting ground to making your own system, such as running commands by Discord bot or hosting your own service. It's not overly tricky to remotely run commands, a few days of works tops for a pre-existing discord bot, but something of the WebPanels level? That'll take a few weeks.

**Comment by coasterteam** [comment]
> The source for the web panel (inside Adonis) is in the GitHub repository, but the website source isn't and will never be so.

They mean the actual website, not the game-side of it

**Comment by P3tray** [comment]
> > The source for the web panel (inside Adonis) is in the GitHub repository, but the website source isn't and will never be so.
> 
> They mean the actual website, not the game-side of it

Sir:
> The source for the web panel (inside Adonis) is in the GitHub repository, but the website source isn't and will never be so.
Reason I know this is because I already asked to help with development, but nobody other him and Scel get a peek at any source code.

**Comment by moo1210** [comment]
The closed-source nature of the web panel is quite odd, Adonis has always been all about open-source and transparency, but the web panel was created in closed source. I feel like development would be a lot better if it was open-source, the current development of the web panel is questionable. I understand there are premium features, however, I don't see why you can't just not release the premium menus.

**Comment by coasterteam** [comment]
@P3tray, that's what I get for not reading the entire thing.

**Comment by P3tray** [comment]
Can this be closed now?
