### ISSUE TITLE
Error in Core > Admin

### ISSUE THREAD

**Issue by gmoddev** [Sceleratis/Adonis#575]
So i've modified adonis a little bit, but i didnt test commands for a while, now im getting this

Its on Core > Admin - 999

Since its modified, i would like to know where i would possibly start looking for the cause
`   
for alias,cmd in pairs(Settings.Aliases) do -- error here
	print(Settings.Aliases)
	local tAlias = stripArgPlaceholders(alias)
	if not CheckAliasBlacklist(tAlias) then
		local escAlias = EscapeSpecialCharacters(tAlias)
		if string.match(msg, "^"..escAlias) or string.match(msg, "%s".. escAlias) then
			msg = FormatAliasArgs(alias, cmd, msg);
		end
	end
end

`

**Comment by gmoddev** [comment]
Oh and i should mention the error happens when running any command

**Comment by CommodoreGamer118** [comment]
I don't think Settings.Aliases is a thing that even exists, I would suggest adding it yourself since it's a modded fork

**Comment by Sceleratis** [comment]
> I don't think Settings.Aliases is a thing that even exists, I would suggest adding it yourself since it's a modded fork

It does

**Comment by LolloDev5123** [comment]
You should ask for help in the Discord server, issues here are related to Adonis itself and not modified versions. But we can help you: https://discord.gg/qBdtcdEXzz

**Comment by P3tray** [comment]
Can we mark this as closed?
