### ISSUE TITLE
"!donorneon" Does not work.

### ISSUE THREAD

**Issue by spaggos** [Sceleratis/Adonis#596]
While I was messing around in a game with donator commands I noticed that the !neon/!donorneon command did not work.

So I took the open source Adonis MainModule and found the reason as to why it kept returning an error even if it was given a valid BrickColor.

![adonisbug](https://user-images.githubusercontent.com/95963635/145674244-4abc8a4c-8729-4c4b-823c-886bd3946e62.PNG)

I tried removing the .Color and the command seemed to work just fine with no error. 

If anyone with access to the Adonis MainModule could possibly fix this I would be glad.

**Comment by GalacticInspired** [comment]
you can become a contributor by forking adonis and fixing it and then making a pull request!

**Comment by spaggos** [comment]
alright, I sent a pull request.
I might've done it wrong since this is my first time using github, let me know if I didn't mess up though.

**Comment by GalacticInspired** [comment]
all correct

**Comment by LolloDev5123** [comment]
Close this issue
