### ISSUE TITLE
Running commands without a Character

### ISSUE THREAD

**Issue by Mudock-Yatho** [Sceleratis/Adonis#6]
![image](https://user-images.githubusercontent.com/24907394/40988245-3b61aad8-68b0-11e8-9919-e0f090456494.png)

Probably be best to set a variable and do something like this:
`
local C=Plr.Character or Plr.CharacterAdded:Wait()
`

**Comment by chexburger** [comment]
Commands properly error when no character is present. Should be marked as resolved.
![image](https://user-images.githubusercontent.com/15860911/124405943-35a87080-dcfd-11eb-9105-60a7956228d1.png)
