### ISSUE TITLE
Dex stopped working

### ISSUE THREAD

**Issue by BlueMeta** [Sceleratis/Adonis#616]
The **:dex** command seem to not work anymore but it loads the GUI and the explorer tab is blank.
I've tried the command in friend's game and my game but the explorer tab is still blank which is strange because it used to work yesterday.
And this is what I've saw in the console.
![Screenshot_20211219_140227-1](https://user-images.githubusercontent.com/34489370/146686636-ea7b27d9-1508-49a1-abdf-2d6d10bd7189.png)
And Dex too.
![Screenshot_20211219_143341](https://user-images.githubusercontent.com/34489370/146686751-e0470bd8-1a30-4635-b18c-0a8c71fbf077.png)

**Comment by fxeP1** [comment]
Should be fixed in next update (v232)

**Comment by coasterteam** [comment]
Fixed
