### ISSUE TITLE
Make Adonis UI use DisplayOrder

### ISSUE THREAD

**Issue by NNickey** [Sceleratis/Adonis#62]
Roblox new features behind yo back

https://wiki.roblox.com/index.php?title=API:Class/ScreenGui/DisplayOrder

set it to like 10 pls

pls implement fast, can't really do a pull request since this github doesn't put everything in it, maybe idk, im lazy yay.

**Comment by Sceleratis** [comment]
Implementing this for the Window GUI now, with support for bringing windows to front when you click in them or drag them.
