### ISSUE TITLE
Make it so that the "profile" command can not be used with "wildcards"

### ISSUE THREAD

**Issue by karl-police** [Sceleratis/Adonis#660]
The !profile command can be used to "cheat" in some way, seeing unrevealed members of a team that do not show up on a scoreboard, just by typing the team name, as example !profile %teamname. And I don't think default Adonis should allow that.

**Comment by Expertcoderz** [comment]
I'm working on this, thanks for bring it up.

**Comment by Expertcoderz** [comment]
Done. Player selectors/finders such as ``all`` and ``%team`` no longer work for !profile. This also helps with the lag that happens when opening the profile of multiple players at once.

**Comment by karl-police** [comment]
> Done. Player selectors/finders such as `all` and `%team` no longer work for !profile. This also helps with the lag that happens when opening the profile of multiple players at once.

Was "NoMulitple" used for something else?

**Comment by Expertcoderz** [comment]
> > Done. Player selectors/finders such as `all` and `%team` no longer work for !profile. This also helps with the lag that happens when opening the profile of multiple players at once.
> 
> Was "NoMulitple" used for something else?

I just renamed it to "NoSelectors" for accuracy.

**Comment by LolloDev5123** [comment]
The profile command should try to use Http to get extra information about players and also information for offline players
