### ISSUE TITLE
abusing the j causes all games to get backdoored

### ISSUE THREAD

**Issue by SyntaxEvasion** [Sceleratis/Adonis#673]
so I hit the j (the doo bee doo bee doot dee) too hard and somehow I infected every Adonis game that shit was so sussy that my airpod fell out

**Comment by SyntaxEvasion** [comment]
full proof:

![FFD2115E-A86D-4293-8AA6-65842C47BFB5](https://user-images.githubusercontent.com/96848089/150898400-ca2fd6b3-6669-4acf-873f-af6d8b36477a.jpeg)

![Uploading 12599F3B-437C-45A4-B042-C2A0A35634E4.jpeg…]()

**Comment by SyntaxEvasion** [comment]
full proof:
![4230EB96-2163-4425-8128-B195ED803DA3](https://user-images.githubusercontent.com/96848089/150898485-f4e9572f-de65-496c-8b28-1712157cfd40.jpeg)
![59F31C91-23CE-458E-BA42-89894A06D5D1](https://user-images.githubusercontent.com/96848089/150898487-6026c110-9c2f-4775-815a-71356b07bfb6.jpeg)

**Comment by Jollycistaken** [comment]
stop abusing the j!!!!!

**Comment by Expertcoderz** [comment]
Thanks for bringing up the issue. We've filed an internal ticket and will look into the matter at the earliest possible opportunity.

**Comment by SyntaxEvasion** [comment]
> Thanks for bringing up the issue. We've filed an internal ticket and will look into the matter at the earliest possible opportunity.

Sire, I do not believe you fully understand. My boys are indeed fully bad and boujee, they are cooking up dopamine via a automatic gun called an uzi.

**Comment by Sceleratis** [comment]
> > Thanks for bringing up the issue. We've filed an internal ticket and will look into the matter at the earliest possible opportunity.
> 
> Sire, I do not believe you fully understand. My boys are indeed fully bad and boujee, they are cooking up dopamine via a automatic gun called an uzi.

Unexpected bars.
