### ISSUE TITLE
Client Sided Tools Detection Deletes Server Sided Tools

### ISSUE THREAD

**Issue by themanmister** [Sceleratis/Adonis#677]
MainModule/Server/Core/Anti.lua

![image](https://user-images.githubusercontent.com/98659819/151670992-332c02ab-66da-4103-9c48-260133c8e05f.png)

**Comment by Awesomewebm** [comment]
😱 Cheack

**Comment by GalacticInspired** [comment]
Cheack 😱

**Comment by pbstFusion** [comment]
😱 Cheack Sorry what is actually the problem here

**Comment by themanmister** [comment]
it tries to looks for "CheckBackpack" with the tool but because its mispelled it never finds it and deletes the tool as a result

**Comment by pbstFusion** [comment]
![image](https://user-images.githubusercontent.com/64012878/151673538-d84cd2a9-19b4-4044-9b57-4b72d45a1f50.png)
So it was a random

**Comment by Expertcoderz** [comment]
https://github.com/Sceleratis/Adonis/commit/db982e7ee2c1915afb02c1ea936f0fada6a8bcb7
