### ISSUE TITLE
Trying to use runcommand but getting a weird error

### ISSUE THREAD

**Issue by SeyRo1** [Sceleratis/Adonis#686]
I want to use Admin.RunCommandAsPlayer to broadcast a message (since RunCommand doesn't work for me it just return a "Access Denied : RunCommand" 
![image](https://user-images.githubusercontent.com/43076302/152640841-4d92e4e8-661b-4c34-8157-b6c7c1eed58d.png)
)

When I execute the line on a normal server (not studio) i get this : 
![image](https://user-images.githubusercontent.com/43076302/152640797-1a96a5b0-c7dd-4481-b681-847a01c5d55f.png)

It does work, but not when using :crossserver

**Comment by P3tray** [comment]
Line 697 in Admin.lua seems to be related to a recent pull request. Hmm...
![image](https://user-images.githubusercontent.com/31691973/152696563-beb1aea6-8461-49fb-9119-0c2881fdd2d2.png)

**Comment by P3tray** [comment]
Is this because :crossserver uses a fake player, which is a folder, meaning calling functions on the player object doesn't work?

**Comment by P3tray** [comment]
Working on a fix now.

**Comment by P3tray** [comment]
Fixed #690 I believe @SeyRo1
