### ISSUE TITLE
Command console not available for Trello admins on first join

### ISSUE THREAD

**Issue by AmNobCop** [Sceleratis/Adonis#692]
If you have the cmdbar for admin only set to true and you have your admin configured via trello and you are the first to join the server you have to respawn before the admin loads and gives you perms to use cmdbar and see commands.

**Comment by coasterteam** [comment]
We should certainly trigger a refresh of the console when admin-level changes. That'll fix this specific issue, as well as make it so if you temp-mod someone they don't have to reset to see commands in console.

**Comment by Expertcoderz** [comment]
[Fixed](https://github.com/Sceleratis/Adonis/commit/b2733ff49ab30f9170aa65c42e456a49a72aabd2).
