### ISSUE TITLE
Documentation for the API.

### ISSUE THREAD

**Issue by HypheX** [Sceleratis/Adonis#70]
Currently, the API docs are very lacking, I suggest you use the Wiki feature in github to create documentation for all the API features in an organized manner, dividing everything into categories (client, service, _G.Adonis, server) etc.

Then explain all of the things you can do with each one.

I would appreciate this, because I am currently lost trying to make a client plugin.

**Comment by NNickey** [comment]
Why is it that your making a client plugin in the first place?

**Comment by HypheX** [comment]
I cannot reveal details until I complete the task. But imo, it does not matter what I use it for, as there should be documentation for everything regardless.

**Comment by Brandon-Beck** [comment]
For service.Events.CommandRan, command refers to the typed command, WITH the command prefix!
Something I certainly didn't expect. Note, there may be multiple in game commands for a single CommandName, and in the case of plugins, in game commands may conflict and override eachother. Thus, to test if a command is part of SomeCommand, its best to find the actual Command by calling server.Admin.GetCommand()
```lua
-- Will test in a few hrs.
service.Events.CommandRan:connect(function(msg,command) -- command = ":fly"
  if server.Commands.SomeCommand == server.Admin.GetCommand(command) then
    -- SomeCommand was run.
  end
end)
```
Else in order to test if SomeCommand was run, you would have to compare command against all of its in game commands, and hope there are no conflicting Commands intercepting the message.

**Comment by Brandon-Beck** [comment]
Custom Ranks could also use some explaining. I cannot figure out how they work, or where they fall into the Admin Level hierarchy.

Eg. We have 2 custom ranks. 
```lua
settings.CustomRanks = {Fly = {"Someone"}, Build={"Someone"}}; 
```
Now.... what can they do? Are they still part of "Players"? How about "Admins" or "Moderators"?
What if "Someone" was also in "Moderators". From what I know, adonis only accepts one level. Does "Moderators" win, or does the custom rank win?
Can you be part of 2 custom ranks, or only 1? If only 1, how does it decide which when there is a conflict?
If we set a command to a custom rank, who has access to it?
```lua
server.Commands.BuildingTools.AdminLevel = "Build" -- does this work? Think it will, but havn't tested yet
settings.Permissions = {"Fly:Fly"} -- How about this? Honestly had no luck during last test
```
Assuming I did that right, can Players Fly? how about Admins? Moderators? Creator? Owner? Is Fly now a magic command outside of the hierarchy that only the Fly rank can access?
Similarly, can "Fly" rank access commands granted to "Players"? "Admin? "Moderator? etc?

Is it currently possibly to give people multiple ranks/commands? My ultimate goal is to categorize commands by what they do (fly/tp/build/morph) and allow access via gampasses. I think I need to alter the permissions system to do this, but as I had no luck finding the code for custom ranks, I figured I would ask here first.

**Comment by Sceleratis** [comment]
One day.... qq

**Comment by Sceleratis** [comment]
Also, the code for CustomRanks I think is in the command processor itself. Not 100% sure, tho now that it's been over a year I doubt it matters anymore lol.

**Comment by pbstFusion** [comment]
**cough**
