### ISSUE TITLE
Ensure that all HumanoidDescription changes get cloned first and then applied

### ISSUE THREAD

**Issue by karl-police** [Sceleratis/Adonis#706]
Ensure that all HumanoidDescription changes get cloned first and then applied.

I've seen some functions not cloning the HumanoidDescription and instead directly modifying the HumanoidDescription from the player.

This can cause issues, especially if you're changing Idle or Run animations.

**Comment by ccuser44** [comment]
The proper way to do this is via `humanoid:GetAppliedDescription()`
