### ISSUE TITLE
new argument for service.Events.CommandRan

### ISSUE THREAD

**Issue by HypheX** [Sceleratis/Adonis#71]
currently, the function's arguments are:
plr, msg, matched, args, command, index, ran, error, isSystem

I believe that another argument should be added, that contains a table, which in turn contains references to the players that were affected by the command, if any. 

This would be helpful so that plugins don't have to do extra processing for the command's arguments.

**Comment by Kan18** [comment]
The determining of players affected by the command is done inside the command's function, and not in the level that fires CommandRan, and it would be even harder to determine which arguments are players and which are numbers/strings, from the level that fires CommandRan. So this would be really hard to do. You could try to overwrite other functions (etc service.GetPlayers) to find players affected, or overwrite the individual command functions for commands you are trying to listen on, if they are specific commands.

**Comment by NNickey** [comment]
Not really, it just requires listing all the players the command was able
to finish on without an error and returning it. Lots of work however, so I
don't see this being needed.

**Comment by Sceleratis** [comment]
While I understand the usefulness of such a variable, it would require extra code be added to every command that affects players and since a lot of those commands run things in parallel it might not work very well in the end.
