### ISSUE TITLE
Making a client plugin causes error and window doesn't show.

### ISSUE THREAD

**Issue by TheBabinator** [Sceleratis/Adonis#73]
So I'm trying to make a plugin that has a window that just has some text saying what song is currently playing on the client.
I know about the lack of documentation so I look at the example client plugin and fiddle around but no matter how many times I try I get this error in the console:

Module encountered an error while loading: Client: Music
Adonis_Client.Core.UI:212: attempt to call field 'IsMobile' (a nil value)

**Comment by NNickey** [comment]
Show your plugin code?

**Comment by Sceleratis** [comment]
Code not provided. Given that this is a plugin, and given that this is now old, I'm closing it as it's likely user-error rather than an actual Adonis issue.
