### ISSUE TITLE
Banned from my own game, can not get unbanned?

### ISSUE THREAD

**Issue by SpiralGaia** [Sceleratis/Adonis#754]
Hello! I was playing around with a Discord to Roblox ban system and trying to make it adonis compatible, and somehow I am now permanently banned from my own game. I tried using commands such as :unpban, while also using Admin.RemoveBan function in the adonis api. I am not showing in the :bans list and I can only play in studio

It seems like a bug, or maybe I did something wrong. I am unsure.

My guess is that I am somehow located in the ban table that is saved, but I have no clue on how to remove myself from that.

**Comment by DaEnder** [comment]
Have you tried :clearplayerdata <your userid>

**Comment by SpiralGaia** [comment]
I found a fix. I used a script to loop through data stores and remove my userid and name from it manually.

**Comment by coasterteam** [comment]
Glad to hear you were able to solve your issue

**Comment by WaviestBalloon** [comment]
Adding onto this: You can easily add a few commands to your `OnStartup` to unban you in any newly created servers.
```lua
settings.OnStartup = {":unban <USERNAME/ID>"};
```
