### ISSUE TITLE
Adonis does''t register changing commands & aliases

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis#761]
For example
`Commands.InsertList.Commands = {"vehicles","cars"}`

![image](https://user-images.githubusercontent.com/68124053/166136793-eafa9fb4-a6bb-4d33-9d51-4b44d466657c.png)

![image](https://user-images.githubusercontent.com/68124053/166136796-6e6cc1ee-4f65-4cea-b250-8f01636e1daa.png)

The old alises work, meaning Adonises command running thingy doesnt register the change

**Comment by Expertcoderz** [comment]
You gotta call ``server.Admin.CacheCommands()`` after making the change for the new aliases to be registered.
