### ISSUE TITLE
Terrain is not restored when using restoremap.

### ISSUE THREAD

**Issue by mr2meowsYT** [Sceleratis/Adonis#77]
if someone uses nuke i cannot restore the terrain and have to restart the server

**Comment by NNickey** [comment]
Restore map isn't intended to be used anymore as it can break several server sided scripts better to wait for restore map to just place everyone to a temporary map and back into the game.

**Comment by Sceleratis** [comment]
Anyone know if the terrain api stuff lets you get the current state of the terrain and re-apply it later if needed?

**Comment by NNickey** [comment]
You can use range copy and range paste, have no idea.

**Comment by moo1210** [comment]
@Sceleratis Found this on the developer hub (when I was looking at the terrian API) that might help with this, 
```
local terrainRegion = workspace.Terrain:CopyRegion(workspace.Terrain.MaxExtents)
workspace.Terrain:Clear()
wait(5)
workspace.Terrain:PasteRegion(terrainRegion, workspace.Terrain.MaxExtents.Min, true)
```
Not too sure if the wait is important or not.
