### ISSUE TITLE
"Script timeout: exhausted allowed execution time" upon DataStoreReadData task execution. 

### ISSUE THREAD

**Issue by SpiralGaia** [Sceleratis/Adonis#788]
Hello! I have made this report a few times in the server but decided to make a full report here as I feel I finally have enough information it it.

Over the past week, the admin will randomly break upon server start. This isn't 100% but it is a pretty high chance and causing lots of issues.

We found that it was a problem with the "DataStoreReadData" task, I'm assuming a simple loop error. Fxe believes its an issue with the "Queue" function. 

More info:
![image](https://user-images.githubusercontent.com/45252038/171925619-b542ed8b-6e97-484c-bd73-90884406fe81.png)
(I am using a fork in this image just so I am able to track tasks, same error on original module as well)

**Comment by Sceleratis** [comment]
https://github.com/Sceleratis/Adonis/issues/779
