### ISSUE TITLE
Adonis loads 1/6 of the time in studio play test

### ISSUE THREAD

**Issue by moo1210** [Sceleratis/Adonis#79]
Adonis only loads like 1/6 of the time in studio play test, making it way harder to test my plugins.

**Comment by Kan18** [comment]
Could you check for errors in the console and if there are any, post them here?

**Comment by moo1210** [comment]
None, it acts like its loaded sucessfully, make a message when you unload it too.

**Comment by Sceleratis** [comment]
Make sure you are using **test servers** and NOT solo/play mode. Using a test server with test clients should work without issue for plugin testing.
