### ISSUE TITLE
:dex not saving

### ISSUE THREAD

**Issue by TbOnFoeNemGrave** [Sceleratis/Adonis#791]
so basically i have a game where i use :dex to give people a custom name and before i used to do it and it worked but now when i do it, it wont save when they rejoin

**Comment by Expertcoderz** [comment]
You should use the ``:name`` or ``:displayname`` commands to give players custom overhead names, instead of Dex which is intended for more technical use.

**Comment by TbOnFoeNemGrave** [comment]
no i have custom names ingame like not :name but i use characterstats. Basically they have a lvl and their name and they could possibly get custom name + lvl if they would ask me

**Comment by Expertcoderz** [comment]
> no i have custom names ingame like not :name but i use characterstats. Basically they have a lvl and their name and they could possibly get custom name + lvl if they would ask me

In that case, you should make a custom command for changing players' names easily.

**Comment by Sceleratis** [comment]
I don't know any situation in which this should have ever worked via dex and saved. Dex should be more or less similar to as if it was edited via studio... Unless you have something to set it back when they rejoin, there shouldn't have been anything dex-related that would have handled it automatically unless it was just a weird bug.
