### ISSUE TITLE
"unmod" command future concept idea

### ISSUE THREAD

**Issue by karl-police** [Sceleratis/Adonis#804]
It is weird and confusing that when you type :unmod to remove someone's Moderator permissions, that it says "admin powers have been removed".

Should this command ever get changed in the future, would be useful to have that part considered a bit more cleaned up. Like that it says "moderator powers" or something. I don't know, just an idea. Not really needed right now, a really minor thing.

**Comment by P3tray** [comment]
@Expertcoderz My pull request (#815 ) fixed this.

**Comment by Expertcoderz** [comment]
Thanks @P3tray.

**Comment by karl-police** [comment]
> @Expertcoderz My pull request (#815 ) fixed this.

it didn't, now if you do unadmin it will say removed moderator instead of admin

**Comment by Expertcoderz** [comment]
> > @Expertcoderz My pull request (#815 ) fixed this.
> 
> it didn't, now if you do unadmin it will say removed moderator instead of admin

No, it now says "removed [rank]" where [rank] can be moderator, admin, etc.

**Comment by karl-police** [comment]
> > > @Expertcoderz My pull request (#815 ) fixed this.
> > 
> > 
> > it didn't, now if you do unadmin it will say removed moderator instead of admin
> 
> No, it now says "removed [rank]" where [rank] can be moderator, admin, etc.

I see.
