### ISSUE TITLE
Tamper protection keeps kicking people

### ISSUE THREAD

**Issue by jakewazhere** [Sceleratis/Adonis#805]
I'm unsure how easy it is to reproduce this, however I am getting a lot of reports of kicks, and even the staff for the game I developer for were banning people over it. Can this be looked into?

https://github.com/Sceleratis/Adonis/blob/688f860d2232baec7f54dda14c5751dd41e5da16/MainModule/Client/Core/Anti.lua#L669

![image](https://user-images.githubusercontent.com/98860311/173787180-83b869a9-b7fc-4122-9e4c-e51f3db0b238.png)

**Comment by ccuser44** [comment]
Oh no... not again, I couldn't have predicted it would go this badly.

I think we need to say goodbye to the client side AC. Client side ACs are a defective idea anyways

**Comment by Sceleratis** [comment]
Removed from release.

**Comment by jakewazhere** [comment]
Awesome, I can finally re-enable adonis anticheat!!!!!111 It totally won't break client sided one day again (joke, keep making good stuff guys).
