### ISSUE TITLE
Add user on settings zindex is lower then the user boxes

### ISSUE THREAD

**Issue by moo1210** [Sceleratis/Adonis#82]
On the settings in the userpanel, the zindex is lower than the userboxes, so after you add 3 users you are unable to see the textlabel where you type in the player's userid/username of who you want to add.

**Comment by Sceleratis** [comment]
wait wat

**Comment by moo1210** [comment]
You know how when you click add it shows a input box where you type in a userid, group, username etc. If you already have more then 3 username in there you can't add any via the in-game settings, you have use the command or the settings module.

**Comment by Sceleratis** [comment]
Late reply cuz was just fixing a stupid bug I encountered related to the remote event getting stuff n what not. I see the issue. Fixing now.
