### ISSUE TITLE
I don't see an equal sign here, is it intended to not have one?

### ISSUE THREAD

**Issue by karl-police** [Sceleratis/Adonis#822]
https://github.com/Sceleratis/Adonis/blob/master/MainModule/Server/Commands/Admins.lua#L54

**Comment by fxeP1** [comment]
It is supposed to be like that, If the level is equal or is over the current users rank, we will not rank them.

**Comment by karl-police** [comment]
> It is supposed to be like that, If the level is equal or is over the current users rank, we will not rank them.

but there's no equal sign. there's only < not <=

**Comment by Expertcoderz** [comment]
> > It is supposed to be like that, If the level is equal or is over the current users rank, we will not rank them.
> 
> but there's no equal sign. there's only < not <=

The code checks to make sure the rank to be given is LESS THAN the executor's rank.

If it were <= it'd mean that admins can make other people the same rank as themselves, which is not good.
