### ISSUE TITLE
DataStore not saving any data

### ISSUE THREAD

**Issue by DJKNIEF** [Sceleratis/Adonis#855]
- Every time I warn/ban/blacklist/whitelist a Player it shows normally in the Player Warnings list, but after a Rejoin or Server Shutdown all data deleted / the Player Warnings list is Empty.

- That after a Rejoin or Server Shutdown all date still saved and accessible.

- All data deleted / Player Warnings list is empty.

- I can't moderate my game well because all data is getting deleted.

**Comment by DJKNIEF** [comment]
![Screenshot 2022-07-13 135426](https://user-images.githubusercontent.com/109217788/178727776-997b1025-9576-4a95-8a26-4599cce54e8e.png)

**Comment by DJKNIEF** [comment]
Now Anti-Cheat doesn't work too.

**Comment by Expertcoderz** [comment]
> Now Anti-Cheat doesn't work as well.

No, you gotta post a separate bug report for that.

**Comment by DJKNIEF** [comment]
I will

**Comment by DJKNIEF** [comment]
I have an example video: https://streamable.com/e6g43o

**Comment by Expertcoderz** [comment]
Fixed (I think).

Reopen is this issue still occurs again in new servers.

**Comment by DJKNIEF** [comment]
So, now the warnings doesn't save, but the bans do save.

**Comment by Expertcoderz** [comment]
> So, now the warnings doesn't save, but the bans do save.

Alright, will investigate.

**Comment by DJKNIEF** [comment]
Thanks
