### ISSUE TITLE
Moderators ranked in-game using :mod/:setrank fail to save across servers

### ISSUE THREAD

**Issue by Expertcoderz** [Sceleratis/Adonis#857]
One would normally expect ``:mod <player>``/``:setrank <player> Moderators`` to save and ``:tempmod <player>`` to not save across servers.

However, after giving a player moderator perms using ``:mod <player>``/``:setrank <player> Moderators``, those perms appear to be lost in a new server instance.

This issue is consistent, but does not seem to extend to ``:admin <player>``.

**Comment by Expertcoderz** [comment]
> 👋 Welcome! It looks like this is your first issue submission here. Please make sure you've included all necessary details in your post so we can reach a resolution as painlessly as possible! Also note that not recieving a response does not mean that your issue has been ignored!

Lol.

**Comment by pnlmon** [comment]
Maybe it's related to #855
