### ISSUE TITLE
Using massbring command launches player into void on occasion

### ISSUE THREAD

**Issue by Lethalitics** [Sceleratis/Adonis#864]
When the massbring command is used on just one player without args[2] then the player gets thrown into the void.

Replicated in 2 player local server by:
massbring player2

To clarify, massbring player2 (any number) will work, and so will doing massbring player1,player2. The only issue occurs when just one player is listed and there is no args[2] supplied.

**Comment by Expertcoderz** [comment]
[Fixed](https://github.com/Sceleratis/Adonis/commit/3f108ef8cb475e11d8636e687245c14abce20176).
