### ISSUE TITLE
Alter guis removed with clearguis

### ISSUE THREAD

**Issue by IoIDogs** [Sceleratis/Adonis#865]
Currently, clearguis deletes guis made by notify and pm, but does not remove guis made by the n command. I believe functionally it makes more sense to not remove notify and pm boxes, but to remove n (as h and m messages are removed).

I find myself usually using the clearguis command when I have accidentally used the m, h, or n commands, but not ever when I accidentally use the notify or pm commands. Using the clearguis command currently puts important pms or notify boxes at risk, when it really is used just to remove unnecessary n, m, h, or alert frames.

**Comment by Expertcoderz** [comment]
I agree with your suggestion; [a change](https://github.com/Sceleratis/Adonis/commit/e68ab363cc5a11003b5ab05d84af9d76859dd082) has been made accordingly and will be available in the next patch release.
