### ISSUE TITLE
Adonis will not remove an admin if they have not joined the server once and there is an item assigned to a rank

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#88]
Adonis will not remove an admin if they have not joined the server once and there is an item assigned to a rank. Instead it will return this error:
<img width="698" alt="Screen Shot 2020-04-01 at 11 15 07 pm" src="https://user-images.githubusercontent.com/62996935/78136181-ebd43900-746e-11ea-8eb1-3baeae359f89.png">

**Comment by Sceleratis** [comment]
This *should* be fixed in the next update

**Comment by MrSaturnss** [comment]
This didn't get fixed. It still has this bug.

**Comment by MrSaturnss** [comment]
This didn't get fixed. Adonis still has the same issue.

**Comment by NNickey** [comment]
The next update probably hasn't released yet, use the version command in-game and wait for that version number to change.

**Comment by Sceleratis** [comment]
The changes made in the update that was released the day I closed this should have stopped this error from happening at all.
