### ISSUE TITLE
Searching for things in :logs results in command timestamps being duplicated

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#89]
Searching for things in :logs results in command timestamps being duplicated. If you search for anything over and over again it will result in timestamps being spammed.
<img width="394" alt="Screen Shot 2020-04-01 at 11 21 44 pm" src="https://user-images.githubusercontent.com/62996935/78136902-15da2b00-7470-11ea-8ca6-89a607184963.png">

**Comment by Sceleratis** [comment]
Fixed in next update
