### ISSUE TITLE
Spamming :notify can crash players

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#90]
Spamming :notify can crash players. Admin abusers could use the :repeat command to crash innocent players. Perhaps add a cap to notifications?

**Comment by Sceleratis** [comment]
I suspect this wouldn't be limited to just :notify

While I acknowledge the issue with this, it requires an admin abuser, which would be able to do a lot more than just crash using notify if they wanted to. As always moderation privileges should not be given lightly. That said, I'll also take a look at the notification code and see if something can be changed to reduce the possibility.
