### ISSUE TITLE
API returns 'userdata' value.

### ISSUE THREAD

**Issue by IntelligentCappy** [Sceleratis/Adonis#93]
When I run 
`require(359948692)._G.Adonis.GetLevel(player)`
The returned value is a userdata value.
Does anybody know what's going on here?

This is my script.
`if(require(359948692)._G.Adonis.GetLevel(player) >=1) then
	player.CharacterAdded:Connect(function()
		script.Parent.Visible = true
	end)
end`

**Comment by NNickey** [comment]
Just use
`_G.Adonis.GetLevel(player)`
require is only needed for inserting Adonis.

**Comment by Sceleratis** [comment]
Require is returning the Adonis userdata/metatable function stuff. You either need to enable _G access in Adonis' settings and use _G.Adonis, though making a plugin that handles communication with other scripts would be better.
