### ISSUE TITLE
Process.MaxChatCharacterLimit should just take MaximumMessageLength from chatsettings.

### ISSUE THREAD

**Issue by moo1210** [Sceleratis/Adonis#95]
There could be a slight chance that someone happened to increase the maximum chat length to something higher than 250, while this would be rare, it might really confuse someone why it isn't working.

**Comment by NNickey** [comment]
Or if the limit has been exceeded, post a warning in server logs.

**Comment by Sceleratis** [comment]
Where's this?

**Comment by moo1210** [comment]
@Sceleratis heres an example `print(chatsettings.MaximumMessageLength)` that would print the MaximumMessageLength, so using the same chatsettings variable and chatsettings.MaximumMessageLength this should be able to be used for seeing what the maximum is set to.

**Comment by Sceleratis** [comment]
And this is usable serverside?

**Comment by Sceleratis** [comment]
Also it feels unlikely that anyone would go through the effort to alter that...

**Comment by moo1210** [comment]
Yes, this works on the server-side, I tested it.

**Comment by P3tray** [comment]
Either close this or make a PR.

**Comment by LolloDev5123** [comment]
I agree
