### ISSUE TITLE
Using the explorer to open a directory while having hover text showing can make the hover text stuck on screen

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#98]
I suspect this is not limited to the explorer, but with other GUIs too.
![Screen Shot 2020-04-13 at 12 25 47 pm](https://user-images.githubusercontent.com/62996935/79087308-2cdb2000-7d82-11ea-8447-1445897cc8f4.png)

**Comment by LolloDev5123** [comment]
This is still an issue. A possible solution would be to find a way to make going on the Open button remove the tooltip, since this bug is related to the creator of the tooltip not being there anymore. [BUMP]
Just tested it on Unity, Aero, and BA Themes and this bug is still here.

**Comment by Expertcoderz** [comment]
No longer an issue due to an update having been made (by me lol) that fundamentally changes how the Explorer interface works.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/81153405/174658580-216bc4e8-a047-49a3-9a0a-baa218e4ca29.png">

Yay.
